apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  MINIO_ALIAS: {{ .Values.minio.alias }}
  MINIO_URL: {{ .Values.minio.url }}
  BUCKET: {{ .Values.minio.bucket }}
  UPLOAD_INTERVAL: {{ .Values.minio.upload_interval }}
