apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  annotations:
    avp.kubernetes.io/path: "ocivault"
stringData:
  access-key: {{ .Values.minio.auth.rootUser }}  
  secret-key: {{ .Values.minio.auth.rootPassword  }}  
