elasticsearch:
  esJavaOpts: "-Xms3g -Xmx3g"
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "4Gi"
  volumeClaimTemplate:
    storageClassName: longhorn
    resources:
      requests:
        storage: 1Gi

filestorage:
  storage_size: 1Gi
  storage_class_name: longhorn

identity:
  global:
    host: "sbrciam.{{domain}}"
    sunbird: 
      jwks_uri: "https://sbrciam.{{domain}}/auth/realms/sunbird-rc/protocol/openid-connect/certs"
    base_urls:
      identity: https://sbrc.{{domain}}/identity
      web_did: https://sbrc.{{domain}}/identity
      credential_schema: https://sbrc.{{domain}}/schema
      credential_service: https://sbrc.{{domain}}/credential
    secrets:
      VAULT_SECRET_TOKEN: "{{vault_root_token |b64encode }}"
      DB_URL: "{{db_url |b64encode}}"