elasticsearch:
  esJavaOpts: "-Xms3g -Xmx3g"
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "4Gi"
  volumeClaimTemplate:
    storageClassName: longhorn
    resources:
      requests:
        storage: 1Gi

filestorage:
  storage_size: 1Gi
  storage_class_name: longhorn