activemq-artemis:
  ingress: 
    istio:
      enabled: false
      hosts:
        - activemq.<path:ocivault#openg2p_domain#latest | base64decode> 
      ingressController:
        name: gateway
      prefix: /
  persistence:
    enabled: false
    storageClass: longhorn