
{{- if .Values.kafka_istio_enabled }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{.Values.kafka_hostname }}
  http:
    - route:
        - destination:
            host: kafka-ui
            port:
              number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https

{{- end }}