apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{ .Values.vault_domain }}
  http:
    - route:
        - destination:
            host: vault.vault.svc.cluster.local
            port:
              number: 8200
      headers:
        request:
          set:
            x-forwarded-proto: https