configserver:
  keycloak_admin_passsword: <path:ocivault#mosip_keycloak_admin_password#latest | base64decode>
  keycloak_manager_passsword: <path:ocivault#mosip_keycloak_manager_password#latest | base64decode>
  keycloak_hostname: iam.<path:ocivault#mosip_domain#latest | base64decode>
  postgres_user_password: <path:ocivault#mosip_pg_password#latest | base64decode> 
  domain_name: <path:ocivault#mosip_domain#latest | base64decode>
  activeProfileEnv: default
  gitRepo:
    uri: https://github.com/oci-mosip/mosip-config
    version: oci-v1.2.0.1-B4

artifacts:
  baseUrl: http://artifactory.artifactory:80
  iamAdapter: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  iamAdapterRegproc: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  iamAdapterRegprocExt: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  hsmClientZip: /artifactory/libs-release-local/hsm/client.zip
  cacheProvider: /artifactory/libs-release-local/cache/cache-provider.jar
  runtimeDep: /artifactory/libs-release-local/io/mosip/kernel/
  regprocJars: /artifactory/libs-release-local/clamav/kernel-virusscanner-clamav.jar
  runtimeDepUrl: /artifactory/libs-release-local/io/mosip/kernel/
  preregistrationBundleUrl: /artifactory/libs-release-local/i18n/pre-registration-i18n-bundle.zip
  virusscannerUrl: /artifactory/libs-release-local/clamav/kernel-virusscanner-clamav.jar
  authwrapperUrl: /artifactory/libs-release-local/idp/idp-auth-wrapper/authentication-wrapper.jar
  esignetauthwrapperUrl: /artifactory/libs-release-local/esignet/esignet-wrapper.zip

initcontainer:
  curl_image: <path:ocivault#mosip_curl_image#latest | base64decode> 
  tcp_image: <path:ocivault#mosip_tcp_image#latest | base64decode> 
  imagepullsecret: "ocir"
  registrycred: <path:ocivault#mosip_ocir_secret#latest> 


esignet:
  fullnameOverride: "esignet"

oidc-ui:
  fullnameOverride: "oidc-ui"
  istio:
    enabled: true
    ingressController:
      name: ingressgateway
    gateways:
      - name: oidc-ui-gateway
        protocol: HTTP
        portName: http
        port: 80
    hosts:
      - esignet.<path:ocivault#mosip_domain#latest | base64decode>
    prefix: /
    
  oidc_ui:
    oidc_ui_port: '3000'
    oidc_service_host: 'esignet.esignet'
    configmaps:
      oidc-ui:
        REACT_APP_API_BASE_URL: 'http://esignet.esignet/v1/esignet'
        REACT_APP_SBI_DOMAIN_URI: 'http://esignet.esignet'
        OIDC_UI_PUBLIC_URL: ''
        SIGN_IN_WITH_ESIGNET_PLUGIN_URL: 'http://artifactory.artifactory:80/artifactory/libs-release-local/mosip-plugins/sign-in-with-esignet.zip'
        DEFAULT_WELLKNOWN: '%5B%7B%22name%22%3A%22OpenID%20Configuration%22%2C%22value%22%3A%22%2F.well-known%2Fopenid-configuration%22%7D%2C%7B%22name%22%3A%22Jwks%20Json%22%2C%22value%22%3A%22%2F.well-known%2Fjwks.json%22%7D%2C%7B%22name%22%3A%22Authorization%20Server%22%2C%22value%22%3A%22%2F.well-known%2Foauth-authorization-server%22%7D%2C%7B%22name%22%3A%22OpenID%20Credential%20Issuer%22%2C%22value%22%3A%22%2F.well-known%2Fopenid-credential-issuer%22%7D%5D'
        DEFAULT_THEME: ''
        DEFAULT_LANG: 'en'
        DEFAULT_FEVICON: 'favicon.ico'
        DEFAULT_TITLE: 'eSignet'
        DEFAULT_ID_PROVIDER_NAME: 'eSignet'