configserver:
  keycloak_admin_passsword: <path:ocivault#mosip_keycloak_admin_password#latest | base64decode>
  keycloak_manager_passsword: <path:ocivault#mosip_keycloak_manager_password#latest | base64decode>
  keycloak_hostname: iam.<path:ocivault#mosip_domain#latest | base64decode>


initcontainer:
  curl_image: <path:ocivault#mosip_curl_image#latest | base64decode> 
  tcp_image: <path:ocivault#mosip_tcp_image#latest | base64decode> 
  imagepullsecret: "ocir"
  registrycred: <path:ocivault#mosip_ocir_secret#latest> 


esignet:
  fullnameOverride: "esignet"
