---
- name: Remove DNS zone records
  hosts: bastion
  environment:
    OCI_ANSIBLE_AUTH_TYPE: "instance_principal"
  tasks:
    - name: Remove zone records
      oracle.oci.oci_dns_rrset:
        zone_name_or_id: "{{domain}}"
        domain: "{{item}}.{{domain}}"
        rtype: "A"
        state: absent
      with_items:
        - api
        - prereg
        - resident
        - esignet
        - spar
        - grafana
        - keycloak
        - opensearch
        - postgres
        - api-internal
        - activemq
        - kibana
        - regclient
        - admin
        - minio
        - kafka
        - pmp
        - smtp
        - signup
        - compliance
        - odk
        - keymanager

