configserver:
  domain_name: <path:ocivault#mosip_domain#latest | base64decode>
  activeProfileEnv: default
  gitRepo:
    uri: https://github.com/oci-mosip/mosip-config
    version: oci-v1.2.0.1-B4

artifacts:
  baseUrl: http://artifactory.artifactory:80
  iamAdapter: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  iamAdapterRegproc: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  iamAdapterRegprocExt: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  hsmClientZip: /artifactory/libs-release-local/hsm/client.zip
  cacheProvider: /artifactory/libs-release-local/cache/cache-provider.jar
  runtimeDep: /artifactory/libs-release-local/io/mosip/kernel/
  regprocJars: /artifactory/libs-release-local/clamav/kernel-virusscanner-clamav.jar
  runtimeDepUrl: /artifactory/libs-release-local/io/mosip/kernel/
  preregistrationBundleUrl: /artifactory/libs-release-local/i18n/pre-registration-i18n-bundle.zip
  virusscannerUrl: /artifactory/libs-release-local/clamav/kernel-virusscanner-clamav.jar
  authwrapperUrl: /artifactory/libs-release-local/idp/idp-auth-wrapper/authentication-wrapper.jar
  esignetauthwrapperUrl: /artifactory/libs-release-local/esignet/esignet-wrapper.zip


regproc-salt:
  fullnameOverride: "regproc-salt"

regproc-workflow:
  fullnameOverride: "regproc-workflow"

regproc-status:
  fullnameOverride: "regproc-status"


regproc-camel:
  fullnameOverride: "regproc-camel"

regproc-pktserver:
  fullnameOverride: "regproc-pktserver"

regproc-group1:
  fullnameOverride: "regproc-group1"
  persistence:
    storageClass: longhorn
    size: 5Gi 


regproc-group2:
  fullnameOverride: "regproc-group2"

regproc-group3:
  fullnameOverride: "regproc-group3"

regproc-group4:
  fullnameOverride: "regproc-group4"

regproc-group5:
  fullnameOverride: "regproc-group5"

regproc-group6:
  fullnameOverride: "regproc-group6"

regproc-group7:
  fullnameOverride: "regproc-group7"

regproc-trans:
  fullnameOverride: "regproc-trans"

regproc-notifier:
  fullnameOverride: "regproc-notifier"

regproc-reprocess:
  fullnameOverride: "regproc-reprocess"