postgresHost: postgres.<path:ocivault#openg2p_domain#latest | base64decode>

postgresql:
  global:
    storageClass: longhorn
  auth:
    database: "mosippdb"
    password: <path:ocivault#mosip_pg_password#latest | base64decode> 
  resources:
    limits: {}
    requests: 
      cpu: 3000m
      memory: 3000Mi

  primary:
    extendedConfiguration: |
      max_connections=1000
      wal_level=logical
      max_wal_senders=20
      max_replication_slots=10

    initdb:
      scripts:
        create_dbs_and_users.sh: |
            #!/bin/bash
            PGPASSWORD=$POSTGRES_PASSWORD psql -U postgres -d postgres -c "CREATE ROLE bn_keycloak WITH LOGIN NOSUPERUSER CREATEDB CREATEROLE INHERIT REPLICATION CONNECTION LIMIT -1 PASSWORD '"$POSTGRES_PASSWORD"';"
            PGPASSWORD=$POSTGRES_PASSWORD psql -U postgres -d postgres -c "CREATE DATABASE bitnami_keycloak WITH OWNER = bn_keycloak TEMPLATE = template0 ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;"


postgres-init:
  backoffLimit: 6
  dbUserPasswords:
    dbuserPassword: <path:ocivault#mosip_pg_password#latest | base64decode> 

  databases:
    mosip_master:
      enabled: true
      branch: release-1.2.0.1

    mosip_audit:
      enabled: true
      branch: release-1.2.0.1

    mosip_keymgr:
      enabled: true 
      branch: release-1.2.0.1-B4

    mosip_kernel:
      enabled: true
      branch: release-1.2.0.1

    mosip_idmap:
      enabled: true
      branch: release-1.2.0.1

    mosip_prereg:
      enabled: true
      branch: release-1.2.0.1

    mosip_idrepo:
      enabled: true
      branch: release-1.2.0.1

    mosip_ida:
      enabled: true
      branch: release-1.2.0.1

    mosip_credential:
      enabled: true
      branch: release-1.2.0.1

    mosip_regprc:
      enabled: true
      branch: release-1.2.0.x

    mosip_pms:
      enabled: true
      branch: release-1.2.0.1

    mosip_hotlist:
      enabled: true
      branch: release-1.2.0.1

    mosip_resident:
      enabled: true
      branch: release-1.2.0.1

    mosip_toolkit:
      enabled: false
      branch: release-1.x.x
  
    mosip_digitalcard:
      enabled: false
      branch: develop

    mosip_esignet:
      enabled: false
      branch: rlease-1.1.0

    mosip_mockidentitysystem:
      enabled: false
      branch: 0.9.0