
{{- if .Values.logging_istio_enabled }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: opensearch
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{.Values.logging_hostname }}
  http:
    - route:
        - destination:
            host: opensearch-dashboards
            port:
              number: 5601
      headers:
        request:
          set:
            x-forwarded-proto: https

{{- end }}