apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-host
  namespace: {{ .Values.namespace }}
data:
  keycloak-internal-host: keycloak.keycloak
  keycloak-internal-url: http://keycloak.keycloak
  keycloak-external-host: {{ .Values.configserver.keycloak_hostname }}
  keycloak-external-url: https://{{ .Values.configserver.keycloak_hostname }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global
data:
  installation-name: openg2p
  installation-domain: {{ .Values.configserver.domain_name }}
  mosip-version: develop
  mosip-api-host: api.{{ .Values.configserver.domain_name }}
  mosip-api-internal-host: api-internal.{{ .Values.configserver.domain_name }}
  mosip-prereg-host: prereg.{{ .Values.configserver.domain_name }}
  mosip-activemq-host: activemq.{{ .Values.configserver.domain_name }}
  mosip-kibana-host: kibana.{{ .Values.configserver.domain_name }}
  mosip-admin-host: admin.{{ .Values.configserver.domain_name }}
  mosip-regclient-host: regclient.{{ .Values.configserver.domain_name }}
  mosip-minio-host: minio.{{ .Values.configserver.domain_name }}
  mosip-kafka-host: kafka.{{ .Values.configserver.domain_name }}
  mosip-iam-external-host: keycloak.{{ .Values.configserver.domain_name }}
  mosip-postgres-host: postgres.{{ .Values.configserver.domain_name }}
  mosip-pmp-host: pmp.{{ .Values.configserver.domain_name }}
  mosip-resident-host: resident.{{ .Values.configserver.domain_name }}
  mosip-compliance-host: compliance.{{ .Values.configserver.domain_name }}
  mosip-esignet-host: esignet.{{ .Values.configserver.domain_name }}
  mosip-smtp-host: smtp.{{ .Values.configserver.domain_name }}
  mosip-signup-host: signup.{{ .Values.configserver.domain_name }}
  is_glowroot_env: absent

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3
  namespace: {{ .Values.namespace }}
data:
  s3-user-key: {{ .Values.configserver.minio_username }}
  s3-region: {{ .Values.configserver.minio_region }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: activemq-activemq-artemis-share
  namespace: {{ .Values.namespace }}
data:
  activemq-core-port: 61616
  activemq-host: activemq-activemq-artemis.activemq