apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-host
  namespace: {{ .Values.namespace }}
data:
  keycloak-internal-host: keycloak.keycloak
  keycloak-internal-url: http://keycloak.keycloak
  keycloak-external-host: {{ .Values.configserver.keycloak_hostname }}
  keycloak-external-url: https://{{ .Values.configserver.keycloak_hostname }}