apiVersion: v1
kind: Secret
metadata:
  name: softhsm-kernel
  namespace: {{ .Values.namespace }}
data:
  security-pin: {{ .Values.configserver.softhsm_securitypin | b64enc | quote}}

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $index, $client := .Values.configserver.clientSecrets }}
  {{- if $client.secret }}
  {{ $client.name }}: {{ $client.secret | b64enc | quote }}
  {{- else }}
  {{ $client.name }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
data:
  admin-password: {{ .Values.configserver.keycloak_admin_passsword | b64enc | quote}}