apiVersion: v1
kind: Secret
metadata:
  name: softhsm-kernel
  namespace: {{ .Values.namespace }}
data:
  security-pin: {{ .Values.configserver.softhsm_securitypin | b64enc | quote}}

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $index, $client := .Values.configserver.clientSecrets }}
  {{- if $client.secret }}
  {{ $client.name }}: {{ $client.secret | b64enc | quote }}
  {{- else }}
  {{ $client.name }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
data:
  admin-password: {{ .Values.configserver.keycloak_admin_passsword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: db-common-secrets
  namespace: {{ .Values.namespace }}
data:
  admin-password: {{ .Values.configserver.postgres_user_password | b64enc | quote }}


---
apiVersion: v1
kind: Secret
metadata:
  name: s3
  namespace: {{ .Values.namespace }}
data:
  s3-user-secret: {{ .Values.configserver.minio_password | b64enc | quote }}
  s3-pretext-value: {{ .Values.configserver.minio_pretext_value | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: softhsm-ida
  namespace: {{ .Values.namespace }}
data:
  security-pin: {{ .Values.configserver.softhsm_securitypin | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: activemq-activemq-artemis
  namespace: {{ .Values.namespace }}
data:
  security-pin: {{ .Values.configserver.artemis_password | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: msg-gateway
  namespace: {{ .Values.namespace }}
data:
  sms-secret: {{ .Values.configserver.sms_secret | b64enc | quote }}
  smtp-secret: {{ .Values.configserver.smtp_secret | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mosip-captcha
  namespace: {{ .Values.namespace }}
data:
  prereg-captcha-site-key: {{ .Values.configserver.openg2p_pre_reg_captcha_site_key | b64enc | quote }}
  prereg-captcha-secret-key: {{ .Values.configserver.openg2p_pre_reg_captcha_secret_key | b64enc | quote }}
  resident-captcha-site-key: {{ .Values.configserver.openg2p_resident_captcha_site_key | b64enc | quote }}
  resident-captcha-secret-key: {{ .Values.configserver.openg2p_resident_captcha_secret_key | b64enc | quote }}
