---
- name: Import keycloak realm
  hosts: bastion
  tasks:
    - name: Get Token
      shell: |
        keycloak_admin_secret=$(kubectl -n keycloak get secret keycloak -o jsonpath={.data.admin-password} | base64 --decode)
        kubectl -n keycloak exec -it keycloak-0 -- curl -d "client_id=admin-cli" -d "username=admin" -d "password=${keycloak_admin_secret}" -d "grant_type=password" "http://keycloak.keycloak/realms/master/protocol/openid-connect/token" | jq -r '.access_token'
      register: admin_token

    - name: Import realm
      shell: |
        kubectl -n keycloak cp /root/.oci/inventory/openg2p-realm.json keycloak-0:/tmp/new-realm.json
        kubectl -n keycloak exec -it keycloak-0 -- curl -v -H "content-type: application/json" -H "Authorization: Bearer {{admin_token.stdout}}" "http://keycloak.keycloak/admin/realms" -d @/tmp/new-realm.json
        sleep 120
      register: import_realm_result

    - name: Import realm results
      debug:
        msg: "Import Result {{import_realm_result.rc}}"