apiVersion: v1
kind: Namespace
metadata:
  name: captcha
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Secret
metadata:
  name: mosip-captcha
  namespace: captcha
  annotations:
    avp.kubernetes.io/path: "ocivault"
data:
  prereg-captcha-site-key: <openg2p_pre_reg_captcha_site_key>
  prereg-captcha-secret-key: <openg2p_pre_reg_captcha_secret_key>
  resident-captcha-site-key: <openg2p_resident_captcha_site_key>
  resident-captcha-secret-key: <openg2p_resident_captcha_secret_key>
