apiVersion: v1
kind: Namespace
metadata:
  name: msg-gateways
  labels:
    istio-injection: enabled

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: msg-gateway
#   namespace: msg-gateways
# data:
#   sms-host: mock-sms.mock-sms
#   sms-port: 8080
#   sms-username: mock-sms.user
#   smtp-host: mock-smtp.mock-smtp
#   smtp-port: 8025
#   smtp-username: mock-smtp.user

---
apiVersion: v1
kind: Secret
metadata:
  name: msg-gateway
  namespace: msg-gateways
  annotations:
    avp.kubernetes.io/path: "ocivault"
data:
  sms-authkey: <openg2p_sms_authkey>
  sms-secret: <openg2p_sms_secret>
  smtp-secret: <openg2p_smtp_secret>
