apiVersion: v1
kind: Secret
metadata:
  name: softhsm-kernel
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  security-pin: {{ .Values.configserver.softhsm_securitypin | b64enc | quote}}

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
type: Opaque
data:
  {{- range $index, $client := .Values.configserver.clientSecrets }}
  {{- if $client.secret }}
  {{ $client.name }}: {{ $client.secret | b64enc | quote }}
  {{- else }}
  {{ $client.name }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  admin-password: {{ .Values.configserver.keycloak_admin_passsword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: db-common-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  db-dbuser-password: {{ .Values.configserver.postgres_user_password | b64enc | quote }}


---
{{- if .Values.configserver.minio_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: s3
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  s3-user-secret: {{ .Values.configserver.minio_password | b64enc | quote }}
  s3-pretext-value: {{ .Values.configserver.minio_pretext_value | b64enc | quote }}

---
{{- end }}

{{- if .Values.configserver.esignet_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  redis-password: {{ .Values.configserver.esignet_redis_password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: softhsm-esignet
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  security-pin: {{ .Values.configserver.softhsm_securitypin | b64enc | quote }}

---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: softhsm-ida
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  security-pin: {{ .Values.configserver.softhsm_securitypin | b64enc | quote }}

---
{{- if .Values.configserver.activemq_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: activemq-activemq-artemis
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  artemis-password: {{ .Values.configserver.artemis_password | b64enc | quote }}

---
{{- end }}

{{- if .Values.configserver.msg_gateway }}
apiVersion: v1
kind: Secret
metadata:
  name: msg-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  smtp-secret: {{ .Values.configserver.smtp_secret | b64enc | quote }}
  sms-secret: {{ .Values.configserver.sms_secret | b64enc | quote }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: mosip-captcha
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  prereg-captcha-site-key: {{ .Values.configserver.pre_reg_captcha_site_key | b64enc | quote }}
  prereg-captcha-secret-key: {{ .Values.configserver.pre_reg_captcha_secret_key | b64enc | quote }}
  resident-captcha-site-key: {{ .Values.configserver.resident_captcha_site_key | b64enc | quote }}
  resident-captcha-secret-key: {{ .Values.configserver.resident_captcha_secret_key | b64enc | quote }}
  esignet-captcha-site-key: {{ .Values.configserver.esignet_captcha_site_key | b64enc | quote }}
  esignet-captcha-secret-key: {{ .Values.configserver.esignet_captcha_secret_key | b64enc | quote }}