monitoring_stack_istio_enabled: true
grafana_domain: grafana.<path:ocivault#mosip_domain#latest | base64decode>
prometheus_domain: prom.<path:ocivault#mosip_domain#latest | base64decode>

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
  grafana:
    adminPassword: "<path:ocivault#mosip_minio_admin_password#latest | base64decode>"
    dashboards: 
      default:
        ceph-cluster:
          gnetId: 2842
          revision: 18
          datasource: Prometheus
    dashboardProviders:
       dashboardproviders.yaml:
         apiVersion: 1
         providers:
         - name: 'default'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: true
           editable: true
           options:
             path: /var/lib/grafana/dashboards/default
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
      dashboards:
        enabled: true
        label: grafana_dashboard
