monitoring_stack_istio_enabled: true
grafana_domain: grafana.<path:ocivault#mosip_domain#latest | base64decode>
prometheus_domain: prom.<path:ocivault#mosip_domain#latest | base64decode>

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      additionalScrapeConfigs:
      # - job_name: 'process-exporter'
      #   scrape_interval: 10s
      #   static_configs:
      #     - targets:
      #         - 'process-exporter.process-exporter-ns.svc.cluster.local:9256'
      - job_name: 'process-exporter'
        scrape_interval: 10s
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            regex: (.*)
            replacement: ${1}:9256
  grafana:
    adminPassword: "<path:ocivault#mosip_minio_admin_password#latest | base64decode>"
    datasources: 
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Oracle Cloud Infrastructure Metrics
          type: oci-metrics-datasource
          access: proxy
          disableDeletion: true
          editable: true
          jsonData:
            tenancyOCID: <path:ocivault#tenancy_id#latest | base64decode>
            defaultRegion: <path:ocivault#oci_region#latest | base64decode>
            environment: "OCI Instance"

    dashboards: 
      default:
        ceph-cluster:
          gnetId: 2842
          revision: 18
          datasource: Prometheus
        ceph-osd-single:
          gnetId: 5336
          revision: 9
          datasource: Prometheus
        ceph-pools:
          gnetId: 5342
          revision: 9
          datasource: Prometheus
        # minio:
        #   gnetId: 13502
        #   revision: 26
        #   datasource: Prometheus
    dashboardProviders:
       dashboardproviders.yaml:
         apiVersion: 1
         providers:
         - name: 'default'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: true
           editable: true
           options:
             path: /var/lib/grafana/dashboards/default
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
      dashboards:
        enabled: true
        label: grafana_dashboard
    plugins:
      - oci-logs-datasource
      - oci-metrics-datasource
      - grafana-kubernetes-app
      - grafana-worldmap-panel
      - grafana-piechart-panel
      - btplc-status-dot-panel

prometheus-postgres-exporter:
  serviceMonitor:
    enabled: true
  config:
    ## The datasource properties on config are passed through helm tpl function.
    ## ref: https://helm.sh/docs/developing_charts/#using-the-tpl-function
    datasource:
      # Specify one of both datasource or datasourceSecret
      host: <path:ocivault#genpg_host#latest | base64decode>           #  postgres-postgresql.postgres
      user: admin
      password: <path:ocivault#genpg#latest | base64decode> 
      port: "5432"
      database: 'postgres'
      sslmode: require

  extraArgs:
    - "--extend.query-path=/etc/config/queries.yaml"

  extraVolumes:
    - name: custom-queries
      configMap:
        name: postgres-exporter-queries

  extraVolumeMounts:
    - name: custom-queries
      mountPath: /etc/config
      readOnly: true

  extraManifests: 
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: postgres-exporter-queries
        labels:
          name: postgres-exporter-extra
      data:
        queries.yaml: |
          pg_replication_slots_lag:
            query: |
              SELECT
                slot_name,
                slot_type,
                database,
                active,
                pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn) AS replication_lag_bytes
              FROM pg_replication_slots;
            metrics:
              - slot_name:
                  usage: "LABEL"
                  description: "Replication slot name"
              - slot_type:
                  usage: "LABEL"
                  description: "Slot type (physical/logical)"
              - database:
                  usage: "LABEL"
                  description: "Database associated with the slot"
              - active:
                  usage: "LABEL"
                  description: "Whether the slot is actively used"
              - replication_lag_bytes:
                  usage: "GAUGE"
                  description: "Amount of WAL data that has not been consumed by the slot (in bytes)"
          pg_replication_lag:
            query: |
              SELECT pid, client_addr,
                EXTRACT(EPOCH FROM now() - pg_stat_replication.replay_timestamp) AS lag_seconds
              FROM pg_stat_replication
              WHERE replay_timestamp IS NOT NULL;
            master: true
            metrics:
              - pid:
                  usage: "LABEL"
              - client_addr:
                  usage: "LABEL"
              - lag_seconds:
                  usage: "GAUGE"
          pg_replication_slot:
            query: |
              select pid, client_addr, state, sync_state,
                  pg_wal_lsn_diff(sent_lsn, write_lsn) as write_lsn_diff,
                  pg_wal_lsn_diff(sent_lsn, flush_lsn) as flush_lsn_diff,
                  pg_wal_lsn_diff(sent_lsn, replay_lsn) as replay_lsn_diff
              from pg_stat_replication;
            master: true
            metrics:
              - pid:
                  usage: "LABEL"
                  description: "The pid of the process. Used to deduplicate the queries if multiple slots from the same client"
              - client_addr:
                  usage: "LABEL"
                  description: "The replication client"
              - write_lsn_diff:
                  usage: "GAUGE"
                  description: "The write lag in bytes"
              - flush_lsn_diff:
                  usage: "GAUGE"
                  description: "The flush lag in bytes"
              - replay_lsn_diff:
                  usage: "GAUGE"
                  description: "The replay lag in bytes"