apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ocir
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registrycred }}

