configserver:
  softhsm_securitypin: <path:ocivault#mosip_softhsm_security_pin#latest | base64decode>
  keycloak_admin_passsword: <path:ocivault#mosip_keycloak_admin_password#latest | base64decode>
  postgres_user_password: <path:ocivault#mosip_pg_password#latest | base64decode> 
  keycloak_hostname: iam.<path:ocivault#mosip_domain#latest | base64decode>
  domain_name: <path:ocivault#mosip_domain#latest | base64decode>
  minio_enabled: true
  minio_username: admin
  minio_password: <path:ocivault#mosip_minio_admin_password#latest | base64decode>
  minio_pretext_value: ""
  minio_region: ""
  activemq_enabled: true
  artemis_password: ""
  msg_gateway: true
  pre_reg_captcha_site_key: <path:ocivault#mosip_pre_reg_captcha_site_key#latest | base64decode>
  pre_reg_captcha_secret_key: <path:ocivault#mosip_pre_reg_captcha_secret_key#latest | base64decode>
  resident_captcha_site_key: <path:ocivault#mosip_resident_captcha_site_key#latest | base64decode>
  resident_captcha_secret_key: <path:ocivault#mosip_resident_captcha_secret_key#latest | base64decode>
  esignet_captcha_site_key: <path:ocivault#mosip_esignet_captcha_site_key#latest | base64decode>
  esignet_captcha_secret_key: <path:ocivault#mosip_esignet_captcha_secret_key#latest | base64decode>

  clientSecrets:
    - name: mosip_abis_client_secret
      secret: "<path:ocivault#mosip_abis_client_secret#latest | base64decode>"
    - name: mosip_admin_client_secret
      secret: "<path:ocivault#mosip_admin_client_secret#latest | base64decode>"
    - name: mosip_admin_services_client_secret
      secret: "<path:ocivault#mosip_admin_services_client_secret#latest | base64decode>"
    - name: mosip_auth_client_secret
      secret: "<path:ocivault#mosip_auth_client_secret#latest | base64decode>"
    - name: mosip_crereq_client_secret
      secret: "<path:ocivault#mosip_crereq_client_secret#latest | base64decode>"
    - name: mosip_creser_client_secret
      secret: "<path:ocivault#mosip_creser_client_secret#latest | base64decode>"
    - name: mosip_datsha_client_secret
      secret: "<path:ocivault#mosip_datsha_client_secret#latest | base64decode>"
    - name: mosip_ida_client_secret
      secret: "<path:ocivault#mosip_ida_client_secret#latest | base64decode>"
    - name: mosip_misp_client_secret
      secret: "<path:ocivault#mosip_misp_client_secret#latest | base64decode>"
    - name: mosip_partner_client_secret
      secret: "<path:ocivault#mosip_partner_client_secret#latest | base64decode>"
    - name: mosip_partnermanager_client_secret
      secret: "<path:ocivault#mosip_partnermanager_client_secret#latest | base64decode>"
    - name: mosip_pms_client_secret
      secret: "<path:ocivault#mosip_pms_client_secret#latest | base64decode>"
    - name: mosip_policymanager_client_secret
      secret: "<path:ocivault#mosip_policymanager_client_secret#latest | base64decode>"
    - name: mosip_reg_client_secret
      secret: "<path:ocivault#mosip_reg_client_secret#latest | base64decode>"
    - name: mosip_regproc_client_secret
      secret: "<path:ocivault#mosip_regproc_client_secret#latest | base64decode>"
    - name: mosip_resident_client_secret
      secret: "<path:ocivault#mosip_resident_client_secret#latest | base64decode>"
    - name: mosip_prereg_client_secret
      secret: "<path:ocivault#mosip_prereg_client_secret#latest | base64decode>"
    - name: mosip_creser_idpass_client_secret
      secret: "<path:ocivault#mosip_creser_idpass_client_secret#latest | base64decode>"
    - name: mosip_syncdata_client_secret
      secret: "<path:ocivault#mosip_syncdata_client_secret#latest | base64decode>"
    - name: mosip_deployment_client_secret
      secret: "<path:ocivault#mosip_deployment_client_secret#latest | base64decode>"
    - name: mpartner_default_auth_secret
      secret: "<path:ocivault#mpartner_default_auth_secret#latest | base64decode>"
    - name: mosip_idrepo_client_secret
      secret: "<path:ocivault#mosip_idrepo_client_secret#latest | base64decode>"
    - name: mpartner_default_print_secret
      secret: "<path:ocivault#mpartner_default_print_secret#latest | base64decode>"
    - name: mosip_hotlist_client_secret
      secret: "<path:ocivault#mosip_hotlist_client_secret#latest | base64decode>"
    - name: mpartner_default_mobile_secret
      secret: "<path:ocivault#mpartner_default_mobile_secret#latest | base64decode>"
    - name: mpartner_default_digitalcard_secret
      secret: "<path:ocivault#mpartner_default_digitalcard_secret#latest | base64decode>"
    - name: mosip_testrig_client_secret
      secret: "<path:ocivault#mosip_testrig_client_secret#latest | base64decode>"


conf-secrets:
  fullnameOverride: "conf-secrets"

config-server:
  fullnameOverride: "config-server"
  gitRepo:
    uri: https://github.com/oci-mosip/mosip-config
    version: oci-v1.2.0.1-B2
    ## Folders within the base repo where properties may be found.
    searchFolders: ""
    private: false
    ## User name of user who has access to the private repo. Ignore for public repo
    username: ""
    token: ""
