kafka_istio_enabled: false
kafka_hostname: kafka.<path:ocivault#openg2p_domain#latest | base64decode> 

kafka-ui:
  envs:
    config:
      SERVER_maxHttpHeaderSize: "200000"
      KAFKA_CLUSTERS_0_NAME: main
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://debezium-service.reporting:8083
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_1_ADDRESS: http://es-connect.reporting:8083
      KAFKA_CLUSTERS_0_KAFKACONNECT_1_NAME: es-connect
      KAFKA_CLUSTERS_1_NAME: ml
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka.ml:9092
  image:
    pullPolicy: Always


kafka:
  extraConfig: |-
    log.retention.hours=2
    default.replication.factor=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    auto.create.topics.enable=true
    delete.topic.enable=true
    num.partitions=5

  controller:
    resources:
      limits: {}
      requests:
        cpu: 200m
        memory: 1500Mi

  broker:
    persistence:
      enabled: false

  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
