
common:
  dns_record_enabled: true
  monitoring_enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

external:
  postgres_enabled: true
  keycloak_enabled: true
  softhsm_enabled: true
  minio_enabled: true
  clamav_enabled: true
  activemq_enabled: true
  kafka_enabled: true
  msg_gw_enabled: true
  captcha_enabled: true
  landingpage_enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

core:
  config_server_enabled: true
  artifactory_enabled: true
  keymanager_enabled: true
  websub_enabled: true
  mock_smtp_enabled: true
  kernel_enabled: true   ## This is not up fully. Idgenerator is giving unique key constraint error
  masterdata_loader_enabled: true
  mock_biosdk_enabled: true
  packetmanager_enabled: true
  datashare_enabled: true
  prereg_enabled: true
  idrepo_enabled: true
  pms_enabled: true
  mock_abis_enabled: true
  mock_mv_enabled: true
  regproc_enabled: true   ### This is not fully up. It has come depenendency with clamav
  admin_enabled: true
  ida_enabled: false
  print_enabled: true
  
  partner_onboarder_enabled: false   ## Partner Onboarding need to be validated manually..
  file_server_enabled: false
  resident_enabled: true
  regclient_enabled: true
  
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD
