external:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD
  components:
    - name: dns-zone-records
      path: workload/mosip/external-modules/dns-zone-records
      namespace: istio-system
      annotations:
        argocd.argoproj.io/sync-wave: "-100"

    - name: httpbin
      path: workload/mosip/external-modules/httpbin
      namespace: istio-system
      annotations:
        argocd.argoproj.io/sync-wave: "-99"

    - name: mosip-monitoring
      repo_url: https://prometheus-community.github.io/helm-charts
      chart_name: kube-prometheus-stack
      chart_version: 65.3.1
      namespace: monitoring
      annotations:
        argocd.argoproj.io/sync-wave: "-98"

    - name: postgres
      path: workload/mosip/external-modules/postgres
      namespace: postgres
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-97"

    - name: postgres-init
      path: workload/mosip/external-modules/postgres-init
      namespace: postgres
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-96"

    - name: keycloak
      path: workload/mosip/external-modules/keycloak
      namespace: keycloak
      namespace_labels:
        istio_injection_label: disabled
      annotations:
        argocd.argoproj.io/sync-wave: "-95"

    - name: softhsm-kernel
      path: workload/mosip/external-modules/softhsm-kernel
      namespace: softhsm
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-94"

    - name: softhsm-ida
      path: workload/mosip/external-modules/softhsm-ida
      namespace: softhsm
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-93"

    - name: minio
      path: workload/mosip/external-modules/minio
      namespace: minio
      namespace_labels:
        istio_injection_label: disabled
      annotations:
        argocd.argoproj.io/sync-wave: "-92"

    - name: clamav
      path: workload/mosip/external-modules/clamav
      namespace: clamav
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-91"

    - name: activemq
      path: workload/mosip/external-modules/activemq
      namespace: activemq
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-90"

    - name: kafka
      path: workload/mosip/external-modules/kafka
      namespace: kafka
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-89"

    - name: msg-gateway
      path: workload/mosip/external-modules/msg-gateway
      namespace: msg-gateways
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-88"

    - name: landing-page
      path: workload/mosip/external-modules/landing-page
      namespace: landing-page
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-87"

core:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD
  components:
    - name: config-server
      path: workload/mosip/core-modules/config-server
      namespace: config-server
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-86"

    - name: artifactory
      path: workload/mosip/core-modules/artifactory
      namespace: artifactory
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-85"

    - name: keymanager
      path: workload/mosip/core-modules/keymanager
      namespace: keymanager
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-84"

    - name: websub
      path: workload/mosip/core-modules/websub
      namespace: websub
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-84"

    - name: mock-smtp
      path: workload/mosip/core-modules/mock-smtp
      namespace: mock-smtp
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-83"

    - name: kernel
      path: workload/mosip/core-modules/kernel
      namespace: kernel
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-82"

    - name: masterdata-loader
      path: workload/mosip/core-modules/masterdata-loader
      namespace: masterdata-loader
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-81"

    - name: mock-biosdk
      path: workload/mosip/core-modules/biosdk
      namespace: biosdk
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-80"

    - name: packetmanager
      path: workload/mosip/core-modules/packetmanager
      namespace: packetmanager
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-79"

    - name: datashare
      path: workload/mosip/core-modules/datashare
      namespace: datashare
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-78"

    - name: pre-registration
      path: workload/mosip/core-modules/prereg
      namespace: prereg
      annotations:
        argocd.argoproj.io/sync-wave: "-77"

    - name: idrepo
      path: workload/mosip/core-modules/idrepo
      namespace: idrepo
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-76"

    - name: pms
      path: workload/mosip/core-modules/pms
      namespace: pms
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-75"

    - name: mock-abis
      path: workload/mosip/core-modules/mock-abis
      namespace: abis
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-74"

    - name: mock-mv
      path: workload/mosip/core-modules/mock-mv
      namespace: abis
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-73"

    - name: registration-processor
      path: workload/mosip/core-modules/regproc
      namespace: regproc
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-72"

    - name: admin
      path: workload/mosip/core-modules/admin
      namespace: admin
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-71"

    - name: ida
      path: workload/mosip/core-modules/ida
      namespace: ida
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-70"

    - name: print
      path: workload/mosip/core-modules/print
      namespace: print
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-71"

    # - name: partner-onboarder
    #   path: workload/mosip/core-modules/xxxx
    #   namespace: xxxx
    #   namespace_labels:
    #     istio_injection_label: enabled


    - name: mosip-file-server
      path: workload/mosip/core-modules/file-server
      namespace: mosip-file-server
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-70"

    - name: resident
      path: workload/mosip/core-modules/resident
      namespace: resident
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-69"

    - name: registration-client
      path: workload/mosip/core-modules/regclient
      namespace: regclient
      namespace_labels:
        istio_injection_label: enabled
      annotations:
        argocd.argoproj.io/sync-wave: "-68"