common:
  dns_record_enabled: true
  monitoring_enabled: true
  keycloak_enabled: false
  postgres_enabled: false
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD