common:
  dns_record_enabled: true
  monitoring_enabled: true
  keycloak_enabled: true
  postgres_enabled: true
  minio_enabled: true
  activemq_enabled: true
  kafka_enabled: true
  msg_gw_enabled: true
  captcha_enabled: true
  landingpage_enabled: true
  config_server_enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

softhsm:
  enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mosip.github.io/mosip-helm
    targetRevision: 12.0.1-B2


## This is not getting deployed. Error install: can't create directory '/run/clamav': Permission denied
clamav:
  enabled: false
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://wiremind.github.io/wiremind-helm-charts
    targetRevision: 2.7.0