external:
  dns_record_enabled: true
  monitoring_enabled: true
  postgres_enabled: true
  keycloak_enabled: true
  softhsm_enabled: true
  minio_enabled: true
  clamav_enabled: true
  activemq_enabled: true
  kafka_enabled: true
  msg_gw_enabled: true
  captcha_enabled: true
  landingpage_enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

core:
  config_server_enabled: true
  keymanager_enabled: false
  websub_enabled: false
  mock_smtp_enabled: false
  kernel_enabled: false   ## This is not up fully. Idgenerator is giving unique key constraint error
  masterdata_loader_enabled: false
  mock_biosdk_enabled: false
  packetmanager_enabled: false
  datashare_enabled: false
  prereg_enabled: false
  idrepo_enabled: false
  pms_enabled: false
  mock_abis_enabled: false
  mock_mv_enabled: false
  regproc_enabled: false   ### This is not fully up. It has come depenendency with clamav
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

artifactory:
  enabled: false
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mosip.github.io/mosip-helm
    targetRevision: 12.0.1-B2
