external:
  postgres_enabled: true
  keycloak_enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

common:
  dns_record_enabled: true
  monitoring_enabled: true
  keycloak_enabled: false
  postgres_enabled: false
  minio_enabled: false
  activemq_enabled: false
  kafka_enabled: false
  msg_gw_enabled: false
  captcha_enabled: false
  landingpage_enabled: false
  config_server_enabled: false
  keymanager_enabled: false
  websub_enabled: false
  mock_smtp_enabled: false
  kernel_enabled: false   ## This is not up fully. Idgenerator is giving unique key constraint error
  masterdata_loader_enabled: false
  mock_biosdk_enabled: false
  packetmanager_enabled: false
  datashare_enabled: false
  prereg_enabled: false
  idrepo_enabled: false
  pms_enabled: false
  mock_abis_enabled: false
  mock_mv_enabled: false
  regproc_enabled: false   ### This is not fully up. It has come depenendency with clamav
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

softhsm:
  enabled: false
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mosip.github.io/mosip-helm
    targetRevision: 12.0.1-B2


artifactory:
  enabled: false
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mosip.github.io/mosip-helm
    targetRevision: 12.0.1-B2


## This is not getting deployed. Error install: can't create directory '/run/clamav': Permission denied
clamav:
  enabled: false
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://wiremind.github.io/wiremind-helm-charts
    targetRevision: 2.7.0