common:
  dns_record_enabled: true
  monitoring_enabled: true
  keycloak_enabled: true
  postgres_enabled: true
  minio_enabled: true
  activemq_enabled: true
  kafka_enabled: true
  msg_gw_enabled: true
  captcha_enabled: true
  landingpage_enabled: true
  config_server_enabled: true
  keymanager_enabled: true
  websub_enabled: true
  mock_smtp_enabled: true
  kernel_enabled: true   ## This is not up fully. Idgenerator is giving unique key constraint error
  masterdata_loader_enabled: true
  mock_biosdk_enabled: true
  packetmanager_enabled: true
  datashare_enabled: true
  prereg_enabled: true
  idrepo_enabled: true
  pms_enabled: true
  mock_abis_enabled: true
  mock_mv_enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

softhsm:
  enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mosip.github.io/mosip-helm
    targetRevision: 12.0.1-B2


artifactory:
  enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mosip.github.io/mosip-helm
    targetRevision: 12.0.1-B2


## This is not getting deployed. Error install: can't create directory '/run/clamav': Permission denied
clamav:
  enabled: false
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://wiremind.github.io/wiremind-helm-charts
    targetRevision: 2.7.0