common:
  dns_record_enabled: true
  monitoring_enabled: true
  keycloak_enabled: true
  postgres_enabled: true
  minio_enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD

softhsm:
  enabled: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mosip.github.io/mosip-helm
    targetRevision: 12.0.1-B2