pg_stat_statements:
  query: "SELECT userid, dbid, queryid, query, calls FROM pg_stat_statements"
  metrics:
    - userid:
        usage: "LABEL"
        description: "User OID"
    - dbid:
        usage: "LABEL"
        description: "Database OID"
    - queryid:
        usage: "LABEL"
        description: "Query ID"
    - calls:
        usage: "COUNTER"
        description: "Number of times executed"
