minio_istio_enabled: true
minio_externalHost: minio.<path:ocivault#mosip_domain#latest | base64decode> 
minio_region: ""
minio_pretext_value: "mosip"
domain_ssl_secret_name: <path:ocivault#openg2p_domain_ssl_secret_name#latest | base64decode>

minio: 
  global:
    storageClass: "ceph-block"
  auth:
    rootUser: admin
    rootPassword: "<path:ocivault#mosip_minio_admin_password#latest | base64decode>"
  persistence:
    size: 10Gi
  # defaultBuckets: "test-bucket"
  nodeSelector: 
    "project": "tally"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  provisioning:
    enabled: true
    nodeSelector: 
      "project": "tally"
    buckets:
      - name: test-bucket
        region: us-east-1
        # Only when mode is 'distributed'
        # Allowed values: "Versioned" | "Suspended" | "Unchanged"
        # Defaults to "Suspended" if not specified.
        # For compatibility, accepts boolean values as well, where true maps
        # to "Versioned" and false to "Suspended".
        # ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
        versioning: Suspended
        # Versioning is automatically enabled if withLock is true
        # ref: https://docs.min.io/docs/minio-bucket-versioning-guide.html
        withLock: false
        # Only when mode is 'distributed'
        # ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
        lifecycle:
          - id: TestPrefix7dRetention
            prefix: test-prefix
            disabled: false
            expiry:
              days: 7
              # Days !OR! date
              # date: "2021-11-11T00:00:00Z"
              nonconcurrentDays: 3
        # Only when mode is 'distributed'
        # ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
        quota:
          # set (hard still works as an alias but is deprecated) or clear(+ omit size)
          type: clear
        tags:
          name: test-bucket