
{{- $config := .Files.Glob "config/*" }}
{{ if $config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openg2p-realm-config
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
{{ tpl (.Files.Glob "config/*").AsConfig .| indent 2 }}
{{ end }}

---
{{- $playbooks := .Files.Glob "playbooks/*" }}
{{ if $playbooks }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-ansible-playbooks
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "playbooks/*").AsConfig | indent 2 }}
{{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-host
  namespace: {{ .Values.namespace }}
data:
  keycloak-internal-host: keycloak.keycloak
  keycloak-internal-url: http://keycloak.keycloak
  keycloak-external-host: {{ .Values.keycloak_hostname }}
  keycloak-external-url: https://{{ .Values.keycloak_hostname }}