
{{- if .Values.keycloak_istio_enabled }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{.Values.keycloak_hostname }}
  http:
    - route:
        - destination:
            host: keycloak
            port:
              number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https

{{- end }}