keycloak_init_enabled: true
keycloak_istio_enabled: true
keycloak_hostname: keycloak.<path:ocivault#openg2p_domain#latest | base64decode> 


realm:
  db_password: <path:ocivault#openg2p_pg_password#latest | base64decode> 


clientSecrets:
  - name: openg2p_admin_client_secret
    secret: <path:ocivault#openg2p_admin_client_secret#latest | base64decode>
  - name: openg2p_selfservice_client_secret
    secret: <path:ocivault#openg2p_selfservice_client_secret#latest | base64decode>
  - name: openg2p_serviceprovider_client_secret
    secret: <path:ocivault#openg2p_serviceprovider_client_secret#latest | base64decode>
  - name: openg2p_minio_client_secret
    secret: <path:ocivault#openg2p_minio_client_secret#latest | base64decode>
  - name: openg2p_kafka_client_secret
    secret: <path:ocivault#openg2p_kafka_client_secret#latest | base64decode>
  - name: openg2p_opensearch_client_secret
    secret: <path:ocivault#openg2p_opensearch_client_secret#latest | base64decode>
  - name: openg2p_superset_client_secret
    secret: <path:ocivault#openg2p_superset_client_secret#latest | base64decode>
  - name: mosip_abis_client_secret
    secret: ""
  - name: mosip_admin_client_secret
    secret: ""
  - name: mosip_admin_services_client_secret
    secret: ""
  - name: mosip_auth_client_secret
    secret: ""
  - name: mosip_crereq_client_secret
    secret: ""
  - name: mosip_creser_client_secret
    secret: ""
  - name: mosip_datsha_client_secret
    secret: ""
  - name: mosip_ida_client_secret
    secret: ""
  - name: mosip_misp_client_secret
    secret: ""
  - name: mosip_pms_client_secret
    secret: ""
  - name: mosip_policymanager_client_secret
    secret: ""
  - name: mosip_reg_client_secret
    secret: ""
  - name: mosip_regproc_client_secret
    secret: ""
  - name: mosip_resident_client_secret
    secret: ""
  - name: mosip_prereg_client_secret
    secret: ""
  - name: mosip_creser_idpass_client_secret
    secret: ""
  - name: mosip_syncdata_client_secret
    secret: ""
  - name: mosip_deployment_client_secret
    secret: ""
  - name: mpartner_default_auth_secret
    secret: ""
  - name: mosip_idrepo_client_secret
    secret: ""
  - name: mpartner_default_print_secret
    secret: ""
  - name: mosip_hotlist_client_secret
    secret: ""
  - name: mpartner_default_mobile_secret
    secret: ""
  - name: mosip_digitalcard_client_secret
    secret: ""
  - name: mpartner_default_digitalcard_secret
    secret: ""
  - name: mosip_testrig_client_secret
    secret: ""
  - name: mpartner_default_opencrvs_secret
    secret: ""


keycloak:
  service:
    type: ClusterIP
    # headless:
    #   extraPorts:
    #     - name: keycloakcli
    #       port: 8080
    #       targetPort: http
    #       protocol: TCP
  
  auth:
    adminUser: admin
    adminPassword: <path:ocivault#openg2p_keycloak_admin_password#latest | base64decode>
  
  ingress:
    enabled: false
  
  replicaCount: 2
  
  proxy: edge
  production: true
  
  resources:
    limits: {}
    requests:
      cpu: 200m
      memory: 1000Mi
  
  rbac:
    create: true
    rules:
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - get
      - list
  
  postgresql:
    enabled: false
  
  keycloakConfigCli:
    extraEnvVars:
      - name: LOGGING_LEVEL_ROOT
        value: debug
      - name: KEYCLOAK_URL
        value: http://keycloak-headless:80/
    enabled: true
    existingConfigmap: openg2p-realm-config

  externalDatabase:
    host: postgres-postgresql.postgres
    database: keycloakdb
    user: keycloakuser
    existingSecret: postgres-postgresql
    existingSecretPasswordKey: password
  