apiVersion: v1
kind: ConfigMap
metadata:
  name: global
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "landing-page,config-server,keymanager,kernel,mock-smtp,websub,biosdk,packetmanager,datashare,prereg,idrepo,abis,pms,regproc,admin,ida,print,resident,esignet,mimoto,inji"
data:
  installation-name: oci-mosip-sandbox
  installation-domain: {{ .Values.domain_name }}
  mosip-version: develop
  mosip-api-host: api.{{ .Values.domain_name }}
  mosip-api-internal-host: api-internal.{{ .Values.domain_name }}
  mosip-prereg-host: prereg.{{ .Values.domain_name }}
  mosip-activemq-host: activemq.{{ .Values.domain_name }}
  mosip-kibana-host: kibana.{{ .Values.domain_name }}
  mosip-admin-host: admin.{{ .Values.domain_name }}
  mosip-regclient-host: regclient.{{ .Values.domain_name }}
  mosip-minio-host: minio.{{ .Values.domain_name }}
  mosip-kafka-host: kafka.{{ .Values.domain_name }}
  mosip-iam-external-host: iam.{{ .Values.domain_name }}
  mosip-idp-host: idp.{{ .Values.domain_name }}
  mosip-postgres-host: postgres.{{ .Values.domain_name }}
  mosip-pmp-host: pmp.{{ .Values.domain_name }}
  mosip-resident-host: resident.{{ .Values.domain_name }}
  mosip-compliance-host: compliance.{{ .Values.domain_name }}
  mosip-esignet-host: esignet.{{ .Values.domain_name }}
  mosip-smtp-host: smtp.{{ .Values.domain_name }}
  mosip-signup-host: signup.{{ .Values.domain_name }}
  mosip-injiweb-host: injiweb.{{ .Values.domain_name }}
  mosip-injiverify-host: injiverify.{{ .Values.domain_name }}
  mosip-injicertify-host: injicertify.{{ .Values.domain_name }}
  mosip-healthservices-host: healthservices.{{ .Values.domain_name }}
  mosip-inji-datashare-host: datashare-inji.injiweb
  is_glowroot_env: absent