ansibleenv:
  zone_compartment_id: <path:ocivault#zone_compartment_id#latest | base64decode>
  domain: <path:ocivault#openg2p_domain#latest | base64decode>

ssl_secret_name: {{ .Values.ansibleenv.domain | replace "." "-" }}