{{- if .Values.common.captcha_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: captcha
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.common.destination.server }}
    namespace: captcha
  project: default
  source:
    repoURL: {{ .Values.common.source.repoURL }}
    targetRevision: {{ .Values.common.source.targetRevision }}
    path: workload/mosip/external-modules/captcha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true  
{{- end }}