{{- if .Values.external.clamav_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clamav
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.external.destination.server}}
    namespace: clamav
  project: default
  source:
    repoURL: {{ .Values.external.source.repoURL}}
    targetRevision: {{ .Values.external.source.targetRevision }}
    path: workload/mosip/external-modules/clamav
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata: 
      labels:
        istio-injection: enabled   
{{- end }}