{{- if .Values.common.dns_record_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-zone-records
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.common.destination.server }}
    namespace: istio-system
  project: default
  source:
    repoURL: {{ .Values.common.source.repoURL }}
    targetRevision: {{ .Values.external.source.targetRevision }}
    path: workload/mosip/external-modules/dns-zone-records
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}