{{- if .Values.external.postgres_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-init
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.external.destination.server }}
    namespace: postgres
  project: default
  source:
    repoURL: {{ .Values.external.source.repoURL }}
    targetRevision: {{ .Values.external.source.targetRevision }}
    path: workload/mosip/external-modules/postgres-init
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}