{{- if .Values.core.prereg_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prereg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.core.destination.server }}
    namespace: prereg
  project: default
  source:
    repoURL: {{ .Values.core.source.repoURL }}
    targetRevision: {{ .Values.core.source.targetRevision }}
    path: workload/mosip/core-modules/prereg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true 
{{- end }}