apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: http-redirect
spec:
  hosts:
    - {{ .Values.domain }}
  gateways:
    - customapp-gw
  http:
    - match:
        - headers:
            x-forwarded-proto:
              exact: http
      redirect:
        scheme: https
        authority: {{ .Values.domain }}
        redirectCode: 301
    - route:
        - destination:
            host: helloworld
            port:
              number: 5000
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: customapp-gw
spec:
  selector:
    istio: ingressgateway-nodeport
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.domain }}
