{{- if .Values.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.istio.destination.server }}
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io                                                              
      kind: ValidatingWebhookConfiguration
      jsonPointers:                                                                                    
      - /webhooks/0/clientConfig/caBundle
      - /webhooks/0/failurePolicy
  project: default
  sources:
    - chart: base
      helm:
        releaseName: istio-base
        values: |
          defaultRevision: default
      repoURL: {{ .Values.istio.source.repoURL }}
      targetRevision: {{ .Values.istio.source.targetRevision }}
    - chart: istiod
      helm:
        releaseName: istiod
      repoURL: {{ .Values.istio.source.repoURL }}
      targetRevision: {{ .Values.istio.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}