{{- if .Values.common.postgres_enabled }}

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: bitnami-postgres-helm-oci
  namespace: argocd
stringData:
  url: registry-1.docker.io/bitnamicharts
  name: postgres
  type: helm
  enableOCI: "true"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.common.destination.server }}
    namespace: postgres
  project: default
  source:
    repoURL: {{ .Values.common.source.repoURL }}
    targetRevision: {{ .Values.common.source.targetRevision }}
    path: workload/id-account-mapper/common/postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}