{{- if .Values.activemq.enabledxxx }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: activemq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.activemq.destination.server }}
    namespace: activemq
  project: default
  source:
    repoURL: {{ .Values.activemq.source.repoURL }}
    targetRevision: {{ .Values.activemq.source.targetRevision }}
    chart: activemq-artemis
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            ingress: 
              istio:
                enabled: false
                hosts:
                  - activemq.<path:ocivault#openg2p_domain#latest | base64decode> 
                ingressController:
                  name: gateway
                prefix: /
            persistence:
              enabled: enabled
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: StatefulSet
      group: apps
      jqPathExpressions:
        - 'spec.replicas'
{{- end }}