{{- if .Values.common.kafka_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.common.destination.server }}
    namespace: kafka
  project: default
  source:
    repoURL: {{ .Values.common.source.repoURL }}
    targetRevision: {{ .Values.common.source.targetRevision }}
    path: workload/id-account-mapper/common/kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}