{{- if .Values.common.logging_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.common.destination.server }}
    namespace: cattle-logging-system
  project: default
  sources:
    - repoURL: {{ .Values.common.source.repoURL }}
      targetRevision: {{ .Values.common.source.targetRevision }}
      path: workload/id-account-mapper/common/logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}