{{- if .Values.artifactory.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.artifactory.destination.server }}
    namespace: artifactory
  project: default
  source:
    repoURL: {{ .Values.artifactory.source.repoURL }}
    targetRevision: {{ .Values.artifactory.source.targetRevision }}
    chart: artifactory
    plugin:
      name: argocd-vault-plugin-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata: 
      labels:
        istio-injection: disabled
{{- end }}