{{- if .Values.opensearch.enabled }}


apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: bitnami-opensearch-helm-oci
  namespace: argocd
stringData:
  url: registry-1.docker.io/bitnamicharts
  name: opensearch
  type: helm
  enableOCI: "true"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.opensearch.destination.server }}
    namespace: cattle-logging-system
  project: default
  source:
    repoURL: {{ .Values.opensearch.source.repoURL }}
    targetRevision: {{ .Values.opensearch.source.targetRevision }}
    chart: opensearch
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            dashboards:
              enabled: true
              replicaCount: 1
              password: <path:ocivault#openg2p_opensearch_dashboard_password#latest | base64decode>
              extraVolumes:
              - name: dashboards-config
                configMap:
                  name: opensearch-conf-files
              extraVolumeMounts:
              - name: dashboards-config
                mountPath: /opt/bitnami/opensearch-dashboards/config/opensearch_dashboards.yml
                subPath: opensearch_dashboards.yml  
            master:
              replicaCount: 1
              persistence:
                size: 8Gi
            data:
              replicaCount: 1
              persistence:
                size: 8Gi
            coordinating:
              replicaCount: 1
            ingest:
              replicaCount: 1
            extraVolumes:
            - name: security-config
              configMap:
                name: opensearch-conf-files
            extraVolumeMounts:
            - name: security-config
              mountPath: /opt/bitnami/opensearch/config/opensearch-security/config.yml
              subPath: opensearch-security-config.yml
            security:
              enabled: true
              tls:
                restEncryption: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}