{{- if .Values.softhsm.enabledxx }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: softhsm-kernel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.softhsm.destination.server }}
    namespace: softhsm
  project: default
  source:
    repoURL: {{ .Values.softhsm.source.repoURL }}
    targetRevision: {{ .Values.softhsm.source.targetRevision }}
    chart: softhsm
    helm:
      releaseName: softhsm-kernel
      values: |
        persistence:
          storageClass: longhorn
        resources:
          limits: {}
          requests:
            cpu: 100m
            memory: 20Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}