{{- if .Values.softhsm.enabledxxx }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: softhsm-kernel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.softhsm.destination.server }}
    namespace: softhsm
  project: default
  source:
    repoURL: {{ .Values.softhsm.source.repoURL }}
    targetRevision: {{ .Values.softhsm.source.targetRevision }}
    chart: softhsm
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES      
          value: |
            securityPIN: <path:ocivault#openg2p_softhsm_security_pin#latest>
            persistence:
              storageClass: longhorn
            resources:
              limits: {}
              requests:
                cpu: 100m
                memory: 20Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}