dashboards:
  enabled: true
  replicaCount: 1
  password: <path:ocivault#openg2p_opensearch_dashboard_password#latest | base64decode>
  extraVolumes:
  - name: dashboards-config
    configMap:
      name: opensearch-conf-files
  extraVolumeMounts:
  - name: dashboards-config
    mountPath: /opt/bitnami/opensearch-dashboards/config/opensearch_dashboards.yml
    subPath: opensearch_dashboards.yml  
master:
  replicaCount: 1
  persistence:
    size: 8Gi
data:
  replicaCount: 1
  persistence:
    size: 8Gi
coordinating:
  replicaCount: 1
ingest:
  replicaCount: 1
extraVolumes:
- name: security-config
  configMap:
    name: opensearch-conf-files
extraVolumeMounts:
- name: security-config
  mountPath: /opt/bitnami/opensearch/config/opensearch-security/config.yml
  subPath: opensearch-security-config.yml
security:
  enabled: true
  tls:
    restEncryption: true
