apiVersion: v1
kind: ConfigMap
metadata:
  name: msg-gateway
  namespace: msg-gateways
data:
  sms-host: mock-sms.mock-sms
  sms-port: "8080"
  sms-username: mock-sms.user
  smtp-host: mock-smtp.mock-smtp
  smtp-port: "8025"
  smtp-username: mock-smtp.user

---
apiVersion: v1
kind: Secret
metadata:
  name: msg-gateway
  namespace: msg-gateways
  annotations:
    avp.kubernetes.io/path: "ocivault"
data:
  smtp-secret: <mosip_smtp_secret>
  sms-secret: <mosip_sms_secret>
