---
- name: Update DNS zone records
  hosts: bastion
  environment:
    OCI_ANSIBLE_AUTH_TYPE: "instance_principal"
  tasks:
    - name: Install kubernetes pre requisites
      pip:
        name: 
          - kubernetes

    # - name: Get the service definition
    #   k8s_info:
    #     kind: Service
    #     name: istio-ingressgateway-internal
    #     namespace: istio-system
    #   register: svc_info

    # - name: Initialize updated status
    #   set_fact:
    #     updated_status:
    #       status:
    #         loadBalancer:
    #           ingress: []

    # - name: Print hostnames as a single line
    #   debug:
    #     msg: "{{ hostnames | join(', ') }}"

    # - name: Create ingress list with hostnames
    #   set_fact:
    #     ingress_list: "{{ ingress_list | default([]) + [{'hostname': item}] }}"
    #   loop: "{{ hostnames }}"

    # - name: Populate updated status with the complete ingress list
    #   set_fact:
    #     updated_status: "{{ updated_status | combine({ 'status': { 'loadBalancer': { 'ingress': ingress_list } } }) }}"
        

    # # - name: Populate updated status with hostnames
    # #   set_fact:
    # #     updated_status: "{{ updated_status | combine({ 'status': { 'loadBalancer': { 'ingress': updated_status.status.loadBalancer.ingress + [{'hostname': item}] } } } } ) }}"
    # #   loop: "{{ hostnames }}"

    # - name: Update the service status in Kubernetes
    #   k8s:
    #     state: present
    #     definition: "{{ svc_info.resources[0] | combine(updated_status) }}"
