
{{- if .Values.keycloak_istio_enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
    - "*"
  gateways:
  - istio-system/keycloak
  http:
  - match:
      - uri:
          prefix: /oauth2
    route:
    - destination:
        host: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        host: keycloak
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: keycloak
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.keycloakExternalHost }}

{{- end }}