
{{- if .Values.keycloak_istio_enabled }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{.Values.keycloakExternalHost }}
  http:
    - route:
        - destination:
            host: keycloak
            port:
              number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: keycloak
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - '{{ .Values.keycloakExternalHost }}'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '{{ .Values.keycloakExternalHost }}'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.domain_ssl_secret_name }}
      mode: SIMPLE

{{- end }}