apiVersion: batch/v1
kind: Job
metadata:
  name: check-postgres-readiness
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: postgres-checker
        image: jbergknoff/postgresql-client
        command:
          - 'sh'
          - '-c'
          - 'until pg_isready -U ${DB_USERNAME} -h ${DB_HOSTNAME} -p ${DB_PORT:-5432} -d ${DB_DBNAME:-mosip_master}; do sleep 3; done'
        env: 
          - name: DB_HOSTNAME
            value: "postgres-postgresql.postgres"
          - name: DB_USERNAME
            value: "masteruser"
          - name: DB_DBNAME
            value: "mosip_master"
      restartPolicy: Never
  backoffLimit: 10
