
apiVersion: v1
kind: Secret
metadata:
  name: db-common-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  db-dbuser-password: {{ .Values.configserver.postgres_user_password | b64enc | quote }}

