apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.postgres.destination.server }}
    namespace: cnpg-system
  project: default
  sources:
    - chart: cloudnative-pg
      helm:
        releaseName: cnpg
      repoURL: {{ .Values.postgres.source.repoURL }}
      targetRevision: {{ .Values.postgres.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
