apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.vault.destination.server }}
    namespace: vault
  project: default
  sources:
    - chart: vault
      helm:
        releaseName: vault
        values: |
          server:
            ha:
              enabled: false
      repoURL: {{ .Values.vault.source.repoURL }}
      targetRevision: {{ .Values.vault.source.targetRevision }}

    - repoURL: {{ .Values.commonSetup.source.repoURL }}
      targetRevision: {{ .Values.commonSetup.source.targetRevision }} 
      path: common/vault  

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
