apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: functional-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sunbird-rc
    server: {{ .Values.workload.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.workload.source.repoURL }}
    targetRevision: {{ .Values.workload.source.targetRevision }}
    path: workload/sunbird-rc
    helm:
      values: |
        filestorage:
          filestorageenv:
            MINIO_ROOT_PASSWORD: {{ .Values.workload.filestorage.rootPassword }} 
        storage_size: {{ .Values.workload.filestorage.storageSize }} 
        storage_class_name: {{ .Values.workload.filestorage.storageClass }} 

  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    automated:
      prune: true
      selfHeal: true