apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: functional-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sunbird-rc
    server: {{ .Values.workload.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.workload.source.repoURL }}
    targetRevision: {{ .Values.workload.source.targetRevision }}
    path: workload/sunbird-rc
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    automated:
      prune: true
      selfHeal: true