apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.certmanager.destination.server }}
    namespace: cert-manager
  project: default
  sources:
    - chart: cert-manager
      helm:
        releaseName: cert-manager
        values: |
          installCRDs: true
      repoURL: {{ .Values.certmanager.source.repoURL }}
      targetRevision: {{ .Values.certmanager.source.targetRevision }}

    - chart: cert-manager-webhook-oci
      helm:
        releaseName: cert-manager-webhook-oci
      repoURL: {{ .Values.certmgr-webhook-oci.source.repoURL }}
      targetRevision: {{ .Values.certmgr-webhook-oci.source.targetRevision }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
