istio:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.2
  gateway:
    lbSubet: <path:ocivault#nlb_subnet_oke_k8s_cluster#latest | base64decode>


certmanager:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: 1.15.3


postgres:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.19.0



certmgrwebhookoci:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://dn13.gitlab.io/cert-manager-webhook-oci
    targetRevision: 1.2.1

commonSetup:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ddevadat/gitops-poc
    targetRevision: HEAD