apiVersion: v1
kind: Secret
metadata:
  name: pmm-secret
  labels:
    app.kubernetes.io/name: pmm
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  PMM_ADMIN_PASSWORD: {{ .Values.pmm_admin_password | b64enc | quote }}
type: Opaque
