
{{- if .Values.monitoring_stack_istio_enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-ui
spec:
  hosts:
  - "{{ .Values.grafana_domain }}"
  gateways:
    - istio-system/all-hosts
  http:
  - route:
    - destination:
        host: monitoring-stack-grafana
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https

--- 

# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: prom-ui
# spec:
#   hosts:
#   - "{{ .Values.prometheus_domain }}"
#   gateways:
#     - istio-system/all-hosts
#   http:
#   - route:
#     - destination:
#         host: monitoring-stack-kube-prom-prometheus
#         port:
#           number: 9090
#     headers:
#       request:
#         set:
#           x-forwarded-proto: https

--- 

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pmm-ui
spec:
  hosts:
  - "{{ .Values.pmm_domain }}"
  gateways:
    - istio-system/all-hosts
  http:
  - route:
    - destination:
        host: monitoring-service
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https
{{- end }}