
{{- if .Values.monitoring_stack_istio_enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-ui
spec:
  hosts:
  - "{{ .Values.grafana_domain }}"
  gateways:
    - istio-system/all-hosts
  http:
  - route:
    - destination:
        host: monitoring-stack-grafana
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https


{{- end }}