
{{- if .Values.chao_mesh_istio_enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chaos-mesh-dashboard-ui
spec:
  hosts:
  - "{{ .Values.chao_mesh_domain }}"
  gateways:
    - istio-system/all-hosts
  http:
  - route:
    - destination:
        host: chaos-dashboard
        port:
          number: 2333
    headers:
      request:
        set:
          x-forwarded-proto: https

{{- end }}