apiVersion: batch/v1
kind: Job
metadata:
  name: maint-page-up
  namespace: vault
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: page-up
          image: alpine:latest
          command: ["sleep", "30"]
      restartPolicy: Never
  backoffLimit: 0

