apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-ansible-sa
  namespace: vault
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-ansible-svc-reader
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
- apiGroups: [""]
  resources: ["pods", "services","pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-ansible-svc-reader-binding
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
subjects:
- kind: ServiceAccount
  name: vault-ansible-sa 
  namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-ansible-svc-reader 
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: batch/v1
kind: Job
metadata:
  name: unseal-vault-test
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: vault-ansible-sa
      containers:
      - name: unsealtvault
        image: ghcr.io/oci-sunbird/ociop:latest
        command: ["ansible-playbook"]
        args: ["/root/.oci/playbooks/unseal_vault.yaml", "-i", "/root/.oci/inventory/inventory"]
        volumeMounts:
        - name: inventory-volume
          mountPath: /root/.oci/inventory
        - name: playbooks-volume
          mountPath: /root/.oci/playbooks
      restartPolicy: Never
      volumes:
      - name: inventory-volume
        configMap:
          name: {{ .Chart.Name }}-ansible-inventory
      - name: playbooks-volume
        configMap:
          name: {{ .Chart.Name }}-ansible-playbooks