configserver:
  domain_name: <path:ocivault#mosip_domain#latest | base64decode>
  activeProfileEnv: default
  gitRepo:
    uri: https://github.com/oci-mosip/mosip-config
    version: oci-v1.2.0.1-B2


mock-abis:
  fullnameOverride: "mock-abis"

