apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: functional-registry-ssl-certificate
  namespace: istio-system
spec:
  dnsNames:
    - "*.<path:ocivault#functional_registry_domain#latest | base64decode>"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  secretName: functional-registry-ssl-certificate
