apiVersion: batch/v1
kind: Job
metadata:
  generateName: update-zone-record
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: updadate-zone-records
          image: alpine:latest
          command: ["sleep", "60"]
      restartPolicy: Never