ansibleenv:
  zone_compartment_id: <path:ocivault#zone_compartment_id#latest | base64decode>
  domain: <path:ocivault#openg2p_domain#latest | base64decode>

domain:  nginx.<path:ocivault#mosip_domain#latest | base64decode> 
domain_ssl_secret_name: <path:ocivault#openg2p_domain_ssl_secret_name#latest | base64decode>


gateway: 
  defaults:
    env: 
      ISTIO_META_IDLE_TIMEOUT: 300s
    label:
        istio: ingressgateway-nodeport    
    service:
      type: NodePort
      ports:
      - name: status-port
        nodePort: 31022
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        nodePort: 31032
        port: 80
        protocol: TCP
        targetPort: 8080
      - name: https
        nodePort: 31712
        port: 443
        protocol: TCP
        targetPort: 8443
