apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - hosts:
    - 'api-internal.{{ .Values.ansibleenv.domain }}'
    port:
      name: http
      number: 80
      protocol: HTTP
---

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol-internal
spec:
  workloadSelector:
    labels:
      app: ingressgateway-internal
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
---

apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: api-internal
spec:
  hosts:
  - 'api-internal.{{ .Values.ansibleenv.domain }}'
  ports:
  - number: 443
    name: http
    protocol: HTTPS
  resolution: DNS