apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-service-account
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-reader
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-reader-binding
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
subjects:
- kind: ServiceAccount
  name: istio-service-account 
  namespace: default
roleRef:
  kind: ClusterRole
  name: service-reader 
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: batch/v1
kind: Job
metadata:
  generateName: update-zone-record
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: istio-service-account
      containers:
      - name: configmanager
        image: ghcr.io/oci-sunbird/ociop:latest
        command: ["ansible-playbook"]
        args: ["/root/.oci/playbooks/update_zone_record_playbook.yaml", "-i", "/root/.oci/inventory/inventory"]
        env:
        - name: OCI_CLI_AUTH
          valueFrom:
            secretKeyRef:
              name: commonsetup-oci
              key: oci_cli_auth
        volumeMounts:
        - name: inventory-volume
          mountPath: /root/.oci/inventory
        - name: playbooks-volume
          mountPath: /root/.oci/playbooks
      restartPolicy: Never
      volumes:
      - name: inventory-volume
        configMap:
          name: commonsetup-conf
      - name: playbooks-volume
        configMap:
          name: commonsetup-playbooks