apiVersion: v1
kind: Namespace
metadata:
  name: sunbird-rc
---
apiVersion: v1
data:
  username: {{ .Values.postgresenv.app_username | b64enc | quote }}
  password: {{ .Values.postgresenv.app_password | b64enc | quote }}
kind: Secret
metadata:
  name: app-secret
  namespace: sunbird-rc
type: kubernetes.io/basic-auth
---

apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: {{ .Values.postgresenv.superuser_password | b64enc | quote }}
kind: Secret
metadata:
  name: superuser-secret
  namespace: sunbird-rc
type: kubernetes.io/basic-auth
---


# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: sunbird-rc
spec:
  instances: {{ .Values.postgresenv.replica }}
  primaryUpdateStrategy: unsupervised
  storage:
    size: {{ .Values.postgresenv.data_size }}
    storageClass: {{ .Values.postgresenv.storage_class }}
  monitoring:
    enablePodMonitor: true

  superuserSecret:
    name: superuser-secret
  bootstrap:
    initdb:
      database: registry
      owner: registry
      secret:
        name: app-secret