apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: sunbird-rc
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{ .Values.functionregistry.keycloak_domain }}
  http:
    - route:
        - destination:
            host: keycloak
            port:
              number: 8080
      headers:
        request:
          set:
            x-forwarded-proto: https
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: identity
  namespace: sunbird-rc
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{ .Values.functionregistry.identity_domain }}
  http: 
  - name: "identity"
    match:
      - uri:
          prefix: "/identity/"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: identity-identity-service
          port: 
            number: 3332
    headers:
      request:
        set:
          x-forwarded-proto: https  
  - name: "schema"
    match:
      - uri:
          prefix: "/schema/"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: identity-credential-schema-service
          port: 
            number: 3333
    headers:
      request:
        set:
          x-forwarded-proto: https  
  - name: "credential"
    match:
      - uri:
          prefix: "/credential/"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: identity-credentials-service
          port: 
            number: 3000
    headers:
      request:
        set:
          x-forwarded-proto: https  
 
--- 

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: filestorage
  namespace: sunbird-rc
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{ .Values.functionregistry.filestorage_domain }}
  http:
    - route:
        - destination:
            host: filestorage
            port:
              number: 9001
      headers:
        request:
          set:
            x-forwarded-proto: https