{{- $config := .Files.Glob "config/*" }}
{{ if $config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mapper-registry-schemas
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
{{ tpl (.Files.Glob "config/*").AsConfig .| indent 2 }}
{{ end }}
