apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
type: Opaque
data:
  password: {{ .Values.postgres.db_password | b64enc | quote }}
