
{{- $config := .Files.Glob "config/*" }}
{{ if $config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openg2p-realm-config
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
{{ tpl (.Files.Glob "config/*").AsConfig .| indent 2 }}
{{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-host
  namespace: {{ .Values.namespace }}
data:
  keycloak-internal-host: keycloak.{{ .Values.namespace }}
  keycloak-internal-url: http://keycloak.{{ .Values.namespace }}
  keycloak-external-host: {{ .Values.keycloak_hostname }}
  keycloak-external-url: https://{{ .Values.keycloak_hostname }}