apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 5432
      name: postgres
      protocol: TCP
    hosts:
    - {{ .Values.postgresHost }}
