apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-host
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  keycloak-internal-host: keycloak.keycloak
  keycloak-internal-url: http://keycloak.keycloak
  keycloak-external-host: {{ .Values.configserver.keycloak_hostname }}
  keycloak-external-url: https://{{ .Values.configserver.keycloak_hostname }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env-vars
  namespace: {{ .Values.namespace }}
data:
  KEYCLOAK_ADMIN_USER: admin
  KEYCLOAK_AUTH_CACHE_OWNERS_COUNT: "1"
  KEYCLOAK_CACHE_OWNERS_COUNT: "1"
  KEYCLOAK_CREATE_ADMIN_USER: "true"
  KEYCLOAK_DATABASE_HOST: postgres-postgresql.postgres
  KEYCLOAK_DATABASE_NAME: bitnami_keycloak
  KEYCLOAK_DATABASE_PORT: "5432"
  KEYCLOAK_DATABASE_USER: bn_keycloak
  KEYCLOAK_ENABLE_STATISTICS: "false"
  KEYCLOAK_ENABLE_TLS: "false"
  KEYCLOAK_HTTP_PORT: "8080"
  KEYCLOAK_JGROUPS_DISCOVERY_PROPERTIES: ""
  KEYCLOAK_JGROUPS_DISCOVERY_PROTOCOL: kubernetes.KUBE_PING
  KEYCLOAK_JGROUPS_TRANSPORT_STACK: tcp
  KEYCLOAK_MANAGEMENT_USER: manager
  KEYCLOAK_PROXY_ADDRESS_FORWARDING: "true"
