apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  admin-password: {{ .Values.configserver.keycloak_admin_passsword | b64enc | quote }}
  management-password: {{ .Values.configserver.keycloak_manager_passsword | b64enc | quote }}

