apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
type: Opaque
data:
  {{- range $index, $client := .Values.configserver.clientSecrets }}
  {{- if $client.secret }}
  {{ $client.name }}: {{ $client.secret | b64enc | quote }}
  {{- else }}
  {{ $client.name }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  admin-password: {{ .Values.configserver.keycloak_admin_passsword | b64enc | quote }}
  management-password: {{ .Values.configserver.keycloak_manager_passsword | b64enc | quote }}

---
{{- if .Values.configserver.minio_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: s3
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  s3-user-secret: {{ .Values.configserver.minio_password | b64enc | quote }}
  s3-pretext-value: {{ .Values.configserver.minio_pretext_value | b64enc | quote }}

---
{{- end }}




