# keymanager_istio_enabled: false
# keymanager_hostname: keymanager.<path:ocivault#openg2p_domain#latest | base64decode> 

configserver:
  domain_name: <path:ocivault#openg2p_domain#latest | base64decode>
  activeProfileEnv: default
  gitRepo:
    uri: https://github.com/oci-sunbird/mosip-config
    version: v.1.0.3

artifacts:
  baseUrl: http://artifactory.artifactory:80
  iamAdapter: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  iamAdapterRegproc: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  iamAdapterRegprocExt: /artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
  hsmClientZip: /artifactory/libs-release-local/hsm/client.zip
  cacheProvider: /artifactory/libs-release-local/cache/cache-provider.jar
  runtimeDep: /artifactory/libs-release-local/io/mosip/kernel/
  regprocJars: /artifactory/libs-release-local/clamav/kernel-virusscanner-clamav.jar
  runtimeDepUrl: /artifactory/libs-release-local/io/mosip/kernel/
  preregistrationBundleUrl: /artifactory/libs-release-local/i18n/pre-registration-i18n-bundle.zip
  virusscannerUrl: /artifactory/libs-release-local/clamav/kernel-virusscanner-clamav.jar
  authwrapperUrl: /artifactory/libs-release-local/idp/idp-auth-wrapper/authentication-wrapper.jar
  esignetauthwrapperUrl: /artifactory/libs-release-local/esignet/esignet-wrapper.zip



mock-identity-system:
  istio:
    enabled: false

  metrics:
    enabled: false

  extraEnvVars:
    - name: softhsm_esignet_security_pin
      valueFrom:
        secretKeyRef:
          name: softhsm-esignet
          key: security-pin
    - name: softhsm_mock_identity_system_security_pin
      valueFrom:
        secretKeyRef:
          name: softhsm-mock-identity-system
          key: security-pin
    - name: esignet_captcha_site_key
      value: ""
    - name: esignet_captcha_secret_key
      value: ""
    - name: mosip_esignet_misp_key
      value: ""

esignet:
  image:
    repository: mosipid/esignet
    tag: 1.2.0
  istio:
    enabled: false

  metrics:
    enabled: false

  extraEnvVars:
    - name: softhsm_esignet_security_pin
      valueFrom:
        secretKeyRef:
          name: softhsm-esignet
          key: security-pin
    - name: softhsm_mock_identity_system_security_pin
      valueFrom:
        secretKeyRef:
          name: softhsm-mock-identity-system
          key: security-pin
    - name: esignet_captcha_site_key
      value: ""
    - name: esignet_captcha_secret_key
      value: ""
    - name: mosip_esignet_misp_key
      value: ""

oidc-ui:
  image:
    repository: mosipid/oidc-ui
    tag: 1.2.0
  istio:
    enabled: false
  oidc_ui:
    configmaps:
      oidc-ui:
        REACT_APP_API_BASE_URL:"http://esignet.esignet/v1/esignet" 
        REACT_APP_SBI_DOMAIN_URI="http://esignet.esignet"
        OIDC_UI_PUBLIC_URL=''