apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
type: Opaque
data:
  {{- range $index, $client := .Values.configserver.clientSecrets }}
  {{- if $client.secret }}
  {{ $client.name }}: {{ $client.secret | b64enc | quote }}
  {{- else }}
  {{ $client.name }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}

