postgres:
  db_password: <path:ocivault#openg2p_pg_password#latest | base64decode> 

domain: <path:ocivault#openg2p_domain#latest | base64decode> 
oidc_client_id: sparclientid
oidc_client_name: SPAR
jwk_private_key: <path:ocivault#openg2p_jwk_private_key#latest> 
jwk_public_key: <path:ocivault#openg2p_jwk_public_key#latest> 

spar:
  global:
    sparHostname: spar.<path:ocivault#openg2p_domain#latest | base64decode>
    esignetBaseUrl: https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>
    sparAuthClientId: 'openg2p-selfservice-client'
    sparAuthClientSecret: <path:ocivault#openg2p_selfservice_client_secret#latest | base64decode>
    keycloakBaseUrl: https://keycloak.<path:ocivault#openg2p_domain#latest | base64decode>
    keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/openg2p'
    sparKeymanagerInstallationName: 'keymanager.keymanager'

  postgresql:
    enabled: false
    istio:
      enabled: false
      virtualservice:
        enabled: false
      gateway:
        enabled: false

  keymanager:
    enabled: false

  spar-mapper-api:
    enabled: true
    global:
      sparHostname: spar.<path:ocivault#openg2p_domain#latest | base64decode>
    postgresql:
      enabled: false
    envVars:
      SPAR_MAPPER_DB_HOSTNAME: postgres-postgresql.postgres
    envVarsFrom:
      SPAR_MAPPER_DB_PASSWORD:
        secretKeyRef:
          name: postgres-postgresql
          key: password

    istio:
      enabled: true
      virtualservice:
        enabled: true
        host: spar.<path:ocivault#openg2p_domain#latest | base64decode>
        gateway: "istio-system/all-hosts"
        destination: '{{ include "mapper.fullname" . }}'
        destinationPort: '{{ .Values.service.port }}'
        prefix: /api/mapper/
        rewriteUri: "/"
      gateway:
        enabled: false
        host: ""
        ingressController:
          istio: gateway
        httpTlsRedirect: true
        httpEnabled: true
        httpsEnabled: false
        tls:
          mode: SIMPLE
          credentialName: ""

  spar-self-service-api:
    enabled: true
    image:
      repository: ghcr.io/oci-sunbird/openg2p-spar-self-service-api
      pullPolicy: Always
      tag: "oci-develop"
    global:
      sparHostname: spar.<path:ocivault#openg2p_domain#latest | base64decode>
    postgresql:
      enabled: false
    postgresInit:
      enabled: false
      envVars:
        GIT_REPO_URL: 'https://github.com/oci-sunbird/openg2p-spar-self-service'
        GIT_BRANCH: 'oci-develop'
    envVars:
      SPAR_SELFSERVICE_DB_HOSTNAME: postgres-postgresql.postgres
      # SPAR_SELFSERVICE_AUTH_DEFAULT_ISSUERS: '["https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>/v1/esignet","https://keycloak.<path:ocivault#openg2p_domain#latest | base64decode>/realms/openg2p"]'
      # SPAR_SELFSERVICE_AUTH_DEFAULT_JWKS_URLS: '["https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>/v1/esignet/oauth/.well-known/jwks.json","https://keycloak.<path:ocivault#openg2p_domain#latest | base64decode>/realms/openg2p/protocol/openid-connect/certs"]'

      SPAR_SELFSERVICE_AUTH_DEFAULT_ISSUERS: '["https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>/v1/esignet"]'
      SPAR_SELFSERVICE_AUTH_DEFAULT_JWKS_URLS: '["https://esignet.<path:ocivault#openg2p_domain#latest | base64decode>/v1/esignet/oauth/.well-known/jwks.json"]'

    envVarsFrom:
      SPAR_SELFSERVICE_DB_PASSWORD:
        secretKeyRef:
          name: postgres-postgresql
          key: password

    istio:
      enabled: true
      virtualservice:
        enabled: true
        host: spar.<path:ocivault#openg2p_domain#latest | base64decode>
        gateway: "istio-system/all-hosts"
        destination: '{{ include "selfservice.fullname" . }}'
        destinationPort: '{{ .Values.service.port }}'
        prefix: /api/selfservice/
        rewriteUri: "/"
      gateway:
        enabled: false
        host: ""
        ingressController:
          istio: gateway
        httpTlsRedirect: true
        httpEnabled: true
        httpsEnabled: false
        tls:
          mode: SIMPLE
          credentialName: ""

  spar-self-service-ui:
    enabled: true
    global:
      sparHostname: spar.<path:ocivault#openg2p_domain#latest | base64decode>
    envVars:
      NEXT_PUBLIC_BASE_PATH: /selfservice
      NEXT_PUBLIC_BASE_API_PATH: /api/selfservice

    istio:
      enabled: true
      virtualservice:
        enabled: true
        host: spar.<path:ocivault#openg2p_domain#latest | base64decode>
        gateway: "istio-system/all-hosts"
        destination: '{{ include "selfserviceUi.fullname" . }}'
        destinationPort: '{{ .Values.service.port }}'
        prefix: /selfservice
        rewriteUri: ""
        # redirectToSelfServiceEnabled: true
      gateway:
        enabled: false
        host: ""
        ingressController:
          istio: gateway
        httpTlsRedirect: true
        httpEnabled: true
        httpsEnabled: false
        tls:
          mode: SIMPLE
          credentialName: ""
