apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{ .Values.functionalregistry.keycloak_domain }}
  http:
    - route:
        - destination:
            host: keycloak
            port:
              number: 8080
      headers:
        request:
          set:
            x-forwarded-proto: https
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{ .Values.functionalregistry.registry_domain }}
  http:
  - name: "registry"
    match:
      - uri:
          prefix: "/registry/"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: registry
          port: 
            number: 8081
    headers:
      request:
        set:
          x-forwarded-proto: https    
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: identity
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{ .Values.functionalregistry.identity_domain }}
  http: 
  - name: "identity"
    match:
      - uri:
          prefix: "/identity/"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: functional-registry-identity-service
          port: 
            number: 3332
    headers:
      request:
        set:
          x-forwarded-proto: https  
  - name: "schema"
    match:
      - uri:
          prefix: "/schema/"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: functional-registry-credential-schema-service
          port: 
            number: 3333
    headers:
      request:
        set:
          x-forwarded-proto: https  
  - name: "credential"
    match:
      - uri:
          prefix: "/credential/"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: functional-registry-credentials-service
          port: 
            number: 3000
    headers:
      request:
        set:
          x-forwarded-proto: https  
 
--- 

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: filestorage
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{ .Values.functionalregistry.filestorage_domain }}
  http:
    - route:
        - destination:
            host: filestorage
            port:
              number: 9001
      headers:
        request:
          set:
            x-forwarded-proto: https