apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      tolerations:
        {{- if .Values.tolerations }}
        {{- toYaml .Values.tolerations | nindent 8 }}
        {{- end }}
      containers:
      {{- range $index, $image := .Values.images }}
        - name: container{{ add $index 1 }}
          image: {{ $image }}
          imagePullPolicy: Always
          command: ["sleep", "3600"]
      {{- end }}
---

apiVersion: v1
kind: List
items:
  {{- range $index, $image := .Values.images }}
  - apiVersion: v1
    kind: Pod
    metadata:
      name: {{ $.Release.Name }}-pod-{{ $index }}
      labels:
        app: {{ $.Release.Name }}-pod-{{ $index }}
    spec:
      nodeSelector:
        {{- range $key, $value := $.Values.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      tolerations:
        {{- if $.Values.tolerations }}
        {{- toYaml $.Values.tolerations | nindent 8 }}
        {{- end }}
      containers:
        - name: container{{ add $index 1 }}
          image: {{ $image }}
          imagePullPolicy: Always
          command: ["sleep", "3600"]
  {{- end }}
