configserver:
  softhsm_securitypin: <path:ocivault#mosip_softhsm_security_pin#latest | base64decode>
  keycloak_admin_passsword: <path:ocivault#mosip_keycloak_admin_password#latest | base64decode>
  keycloak_manager_passsword: <path:ocivault#mosip_keycloak_manager_password#latest | base64decode>
  postgres_user_password: <path:ocivault#mosip_pg_password#latest | base64decode> 
  keycloak_hostname: iam.<path:ocivault#mosip_domain#latest | base64decode>
  domain_name: <path:ocivault#mosip_domain#latest | base64decode>
  minio_enabled: true
  minio_username: admin
  minio_password: <path:ocivault#mosip_minio_admin_password#latest | base64decode>
  minio_pretext_value: ""
  minio_region: ""

  clientSecrets:
    - name: mosip_abis_client_secret
      secret: "<path:ocivault#mosip_abis_client_secret#latest | base64decode>"
    - name: mosip_admin_client_secret
      secret: "<path:ocivault#mosip_admin_client_secret#latest | base64decode>"
    - name: mosip_admin_services_client_secret
      secret: "<path:ocivault#mosip_admin_services_client_secret#latest | base64decode>"
    - name: mosip_auth_client_secret
      secret: "<path:ocivault#mosip_auth_client_secret#latest | base64decode>"
    - name: mosip_crereq_client_secret
      secret: "<path:ocivault#mosip_crereq_client_secret#latest | base64decode>"
    - name: mosip_creser_client_secret
      secret: "<path:ocivault#mosip_creser_client_secret#latest | base64decode>"
    - name: mosip_datsha_client_secret
      secret: "<path:ocivault#mosip_datsha_client_secret#latest | base64decode>"
    - name: mosip_ida_client_secret
      secret: "<path:ocivault#mosip_ida_client_secret#latest | base64decode>"
    - name: mosip_misp_client_secret
      secret: "<path:ocivault#mosip_misp_client_secret#latest | base64decode>"
    - name: mosip_partner_client_secret
      secret: "<path:ocivault#mosip_partner_client_secret#latest | base64decode>"
    - name: mosip_partnermanager_client_secret
      secret: "<path:ocivault#mosip_partnermanager_client_secret#latest | base64decode>"
    - name: mosip_pms_client_secret
      secret: "<path:ocivault#mosip_pms_client_secret#latest | base64decode>"
    - name: mosip_policymanager_client_secret
      secret: "<path:ocivault#mosip_policymanager_client_secret#latest | base64decode>"
    - name: mosip_reg_client_secret
      secret: "<path:ocivault#mosip_reg_client_secret#latest | base64decode>"
    - name: mosip_regproc_client_secret
      secret: "<path:ocivault#mosip_regproc_client_secret#latest | base64decode>"
    - name: mosip_resident_client_secret
      secret: "<path:ocivault#mosip_resident_client_secret#latest | base64decode>"
    - name: mosip_prereg_client_secret
      secret: "<path:ocivault#mosip_prereg_client_secret#latest | base64decode>"
    - name: mosip_creser_idpass_client_secret
      secret: "<path:ocivault#mosip_creser_idpass_client_secret#latest | base64decode>"
    - name: mosip_syncdata_client_secret
      secret: "<path:ocivault#mosip_syncdata_client_secret#latest | base64decode>"
    - name: mosip_deployment_client_secret
      secret: "<path:ocivault#mosip_deployment_client_secret#latest | base64decode>"
    - name: mpartner_default_auth_secret
      secret: "<path:ocivault#mpartner_default_auth_secret#latest | base64decode>"
    - name: mosip_idrepo_client_secret
      secret: "<path:ocivault#mosip_idrepo_client_secret#latest | base64decode>"
    - name: mpartner_default_print_secret
      secret: "<path:ocivault#mpartner_default_print_secret#latest | base64decode>"
    - name: mosip_hotlist_client_secret
      secret: "<path:ocivault#mosip_hotlist_client_secret#latest | base64decode>"
    - name: mpartner_default_mobile_secret
      secret: "<path:ocivault#mpartner_default_mobile_secret#latest | base64decode>"
    - name: mpartner_default_digitalcard_secret
      secret: "<path:ocivault#mpartner_default_digitalcard_secret#latest | base64decode>"
    - name: mosip_testrig_client_secret
      secret: "<path:ocivault#mosip_testrig_client_secret#latest | base64decode>"
    - name: mosip_digitalcard_client_secret
      secret: "<path:ocivault#mosip_digitalcard_client_secret#latest | base64decode>"

initcontainer:
  curl_image: <path:ocivault#mosip_curl_image#latest | base64decode> 
  tcp_image: <path:ocivault#mosip_tcp_image#latest | base64decode> 
  imagepullsecret: "ocir"
  registrycred: <path:ocivault#mosip_ocir_secret#latest> 


partner-onboarder:
  fullnameOverride: "mimoto-onboarding"
  onboarding:
    modules:
      - name: ida
        enabled: false
      - name: print
        enabled: false
      - name: abis
        enabled: false
      - name: resident
        enabled: false
      - name: mobileid
        enabled: false
      - name: digitalcard
        enabled: false
      - name: esignet
        enabled: false
      - name: resident-oidc
        enabled: false
      - name: demo-oidc
        enabled: false
      - name: mimoto-keybinding
        enabled: true
      - name: mimoto-oidc
        enabled: true

    configmaps:
      s3:
        # s3-host: 'https://minio.<path:ocivault#mosip_domain#latest | base64decode>'
        s3-user-key: 'admin'
        s3-region: 'us-east-1'
        s3-bucket-name: 'onboardmimoto'
      onboarder-namespace:
        ns_mimoto: mimoto
        ns_esignet: esignet
      onboarding: 
        ENABLE_INSECURE: false
    secrets: