apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-id-account-mapper-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: argocd/id-account-mapper
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/ddevadat/gitops-poc'
    targetRevision: HEAD
    path: argocd/id-account-mapper
    plugin:
      name: argocd-vault-plugin-helm
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true