apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/ddevadat/gitops-poc'
    targetRevision: HEAD
    path: argocd/apps-helm/
    plugin:
      name: argocd-vault-plugin-helm
      # env:
      #   - name: HELM_VALUES
      #     value: |
      #       istio:
      #         gateway:
      #           lbSubet: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true