apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/ddevadat/gitops-poc'
    targetRevision: HEAD
    path: argocd/apps/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true