configserver:
  postgres_user_password: <path:ocivault#mosip_pg_password#latest | base64decode> 

initcontainer:
  postgres_client_image: <path:ocivault#mosip_postgres_client_image#latest | base64decode> 
  imagepullsecret: "ocir"
  registrycred: <path:ocivault#mosip_ocir_secret#latest> 

masterdata-loader:
  fullnameOverride: "masterdata-loader"
  mosipDataGithubBranch: 1.2.0.1
