
{{- if .Values.custom_virtual_service_enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: landing-page-vs
spec:
  gateways:
  - istio-system/all-hosts
  hosts:
  - '{{ .Values.landing_page_host }}'
  http:
  - headers:
      request:
        set:
          x-forwarded-proto: https
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: landing-page
        port:
          number: 80

{{- end }}