
{{- if .Values.minio_istio_enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: minio
spec:
  hosts:
  - '{{ .Values.minio_externalHost }}'
  gateways:
  - istio-system/all-hosts
  http:
  - name: http
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: minio
        port:
           number: 9001
    headers:
      request:
        set:
          x-forwarded-proto: https

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: minio
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - '{{ .Values.minio_externalHost }}'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '{{ .Values.minio_externalHost }}'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.domain_ssl_secret_name }}
      mode: SIMPLE

{{- end }}