pg_db_user: mosippdb
pg_db_password: <path:ocivault#mosip_pg_password#latest | base64decode> 




postgres-init:
  backoffLimit: 6
  jobAnnotations:
    argocd.argoproj.io/sync-wave: "-96"
  dbUserPasswords:
    dbuserPassword: <path:ocivault#mosip_pg_password#latest | base64decode> 

  databases:
    mosip_master:
      enabled: true
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1
      su:
        user: postgres
        secret:
          name: superuser-secret
          key: password

    mosip_audit:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_keymgr:
      enabled: false 
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1-B4

    mosip_kernel:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_idmap:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_prereg:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_idrepo:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_ida:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_credential:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_regprc:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.x

    mosip_pms:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_hotlist:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_resident:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.2.0.1

    mosip_toolkit:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: release-1.x.x
  
    mosip_digitalcard:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: develop

    mosip_esignet:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: rlease-1.1.0

    mosip_mockidentitysystem:
      enabled: false
      host: "cloudnative-pg-cluster-rw"
      branch: 0.9.0

cluster:
  superuserSecret: "superuser-secret"
  version:
    postgresql: "14"
  cluster:
    instances: 3
    storage:
      size: 8Gi
      storageClass: "longhorn"
    walStorage:
      enabled: false
      size: 1Gi
      storageClass: "longhorn"
    postgresql:
      # -- PostgreSQL configuration options (postgresql.conf)
      parameters:
        max_connections: "1000"
        wal_level: logical
        max_wal_senders: "20"
        max_replication_slots: "10"
      # -- PostgreSQL Host Based Authentication rules (lines to be appended to the pg_hba.conf file)
      pg_hba: 
        - host all all 10.244.0.0/16 md5
      # -- PostgreSQL User Name Maps rules (lines to be appended to the pg_ident.conf file)
      pg_ident: 
        - mymap   /^(.*)@mydomain\.com$      \1
    initdb: 
      database: mosippdb
      owner: mosippdb
      secret:
        name: "postgres-postgresql" 
      postInitSQL:
        - CREATE ROLE bn_keycloak WITH LOGIN NOSUPERUSER CREATEDB CREATEROLE INHERIT REPLICATION CONNECTION LIMIT -1 PASSWORD '<path:ocivault#mosip_pg_password#latest | base64decode>';
        - CREATE DATABASE bitnami_keycloak WITH OWNER = bn_keycloak TEMPLATE = template0 ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;

