storage_class: longhorn
super_username: cassandra
super_user_password: "<path:ocivault#cncf_cassandra_super_user_password#latest | base64decode>"
cassandraHost: cassandra.<path:ocivault#openg2p_domain#latest | base64decode>
cluster:
  version:
    postgresql: "14"
  cluster:
    instances: 3
    storage:
      size: 8Gi
      storageClass: "longhorn"
    walStorage:
      enabled: false
      size: 1Gi
      storageClass: "longhorn"
    postgresql:
      # -- PostgreSQL configuration options (postgresql.conf)
      parameters:
        max_connections: "300"
      # -- PostgreSQL Host Based Authentication rules (lines to be appended to the pg_hba.conf file)
      pg_hba: 
        - host all all 10.244.0.0/16 md5
      # -- PostgreSQL User Name Maps rules (lines to be appended to the pg_ident.conf file)
      pg_ident: 
        - mymap   /^(.*)@mydomain\.com$      \1
