{{- if .Values.keycloak_init_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $index, $client := .Values.clientSecrets }}
  {{- if $client.secret }}
  {{ $client.name }}: {{ $client.secret | b64enc | quote }}
  {{- else }}
  {{ $client.name }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}