apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: native-ic-params
spec:
  compartmentId: {{ .Values.compartment_id }}  
  subnetId: {{ .Values.subnet_id }}  
  loadBalancerName: "native-ic-lb"
  isPrivate: false
  maxBandwidthMbps: 400
  minBandwidthMbps: 100

---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: native-ic-ingress-class
  annotations:
    {{- with .Values.ingress_class_annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    scope: Namespace
    namespace: native-ingress-controller-system
    apiGroup: ingress.oraclecloud.com
    kind: ingressclassparameters
    name: native-ic-params

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-redirect-ingress
  annotations:
    kubernetes.io/ingress.class: native-ic-ingress-class
    oci-native-ingress.oraclecloud.com/http-listener-port: 80
spec:
  rules:
    - host: {{ .Values.domain }} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: http-redirect
                port:
                  number: 80
--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: https-app-ingress
  annotations:
    kubernetes.io/ingress.class: native-ic-ingress-class
    oci-native-ingress.oraclecloud.com/https-listener-port: 443
spec:
  tls:
    - hosts:
        - {{ .Values.domain }} 
      secretName: {{ .Values.domain_ssl_secret_name }} 
  rules:
    - host: {{ .Values.domain }} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-website
                port:
                  number: 443
