apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
spec:
  hosts:
  - {{ .Values.domain | quote}}
  gateways:
  - nginx-gw
  http:
  - name: http
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: nginx-website
        port:
           number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gw
spec:
  selector:
    istio: ingressgateway-nodeport
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
