apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-redirect-config
data:
  default.conf: |
    server {
      listen 80;
      server_name {{ .Values.domain }} ;
      return 301 https://$host$request_uri;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-redirect
  template:
    metadata:
      labels:
        app: http-redirect
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config
          configMap:
            name: nginx-redirect-config
---
apiVersion: v1
kind: Service
metadata:
  name: http-redirect
spec:
  type: NodePort
  selector:
    app: http-redirect
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32080
