apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      containers:
        - name: nginx
          image: nginx:stable
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-website
spec:
  selector:
    app: nginx-website
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
