apiVersion: batch/v1
kind: Job
metadata:
  name: check-softhsm-kernel-readiness
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: readiness-check
        image: curlimages/curl:latest # Using a curl image
        command: ["sh", "-c"]
        args:
          - |
            while true; do
              echo "Checking readiness of softhsm-kernel service...";
              if curl -sf http://softhsm-kernel.softhsm/; then
                echo "Service is ready!";
                exit 0;
              else
                echo "Service is not ready, retrying in 5 seconds...";
                sleep 5;
              fi
            done
      restartPolicy: Never
  backoffLimit: 4
