
{{- $configs := .Files.Glob "configs/*" }}
{{ if $configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-conf
  namespace: {{ .Values.namespace }}
data:
{{ tpl (.Files.Glob "configs/*").AsConfig .| indent 2 }}
{{ end }}

---

{{- $playbooks := .Files.Glob "playbooks/*" }}
{{ if $playbooks }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-playbooks
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "playbooks/*").AsConfig | indent 2 }}
{{ end }}