
{{- $configs := .Files.Glob "configs/*" }}
{{ if $configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-conf
  namespace: {{ .Values.namespace }}
data:
{{ tpl (.Files.Glob "configs/*").AsConfig .| indent 2 }}
{{ end }}