apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customapp-vs
spec:
  hosts:
    - "*"
  gateways:
  - customapp-gw

  http:
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
    headers:
      request:
        set:
          x-forwarded-proto: https

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: customapp-gw
spec:
  selector:
    istio: ingressgateway-nodeport
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.domain }}
