apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-ssl-certificate
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
    - "{{ .Values.ssl.sslDnsNames }}" 
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  secretName: {{ .Chart.Name }}-ssl-certificate
