ansibleenv:
  vault_compartment_id: <path:ocivault#vault_compartment_id#latest | base64decode>
  vault_id: <path:ocivault#vault_id#latest | base64decode>
  vault_key_id: <path:ocivault#vault_key_id#latest | base64decode>

vault_domain: argosbrcvault.<path:ocivault#functional_registry_domain#latest | base64decode>

vault:
  server:
    ha:
      enabled: true
      raft:
        enabled: true