apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Hashicorp-Vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.common.destination.server }}
    namespace: vault
  project: default
  ignoreDifferences:
    - group: '*'                                                              
      kind: '*'
      managedFieldsManagers:                                                                                    
      - vault-k8s
  source:
    repoURL: {{ .Values.common.source.repoURL }}
    targetRevision: {{ .Values.common.source.targetRevision }}
    path: workload/functional-registry/common/vault-ha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
