ceph_istio_enabled: true
ceph_domain: ceph.<path:ocivault#mosip_domain#latest | base64decode>

rook-ceph-cluster:
  monitoring:
    enabled: true
    createPrometheusRules: true
  toolbox:
    enabled: true
    # tolerations: 
    # - key: "node-role.kubernetes.io/rook-node"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # affinity: 
    #   oke.oraclecloud.com/pool.name: rook
  cephClusterSpec:
    removeOSDsIfOutAndSafeToRemove: true
    cleanupPolicy:
      # Since cluster cleanup is destructive to data, confirmation is required.
      # To destroy all Rook data on hosts during uninstall, confirmation must be set to "yes-really-destroy-data".
      # This value should only be set when the cluster is about to be deleted. After the confirmation is set,
      # Rook will immediately stop configuring the cluster and only wait for the delete command.
      # If the empty string is set, Rook will not destroy any data on hosts during uninstall.
      confirmation: "yes-really-destroy-data"
    dashboard:
      enabled: true
      ssl: false
      prometheusEndpoint: http://monitoring-stack-kube-prom-prometheus.monitoring-stack:9090
      prometheusEndpointSSLVerify: false
    mgr:
      # When higher availability of the mgr is needed, increase the count to 2.
      # In that case, one mgr will be active and one in standby. When Ceph updates which
      # mgr is active, Rook will update the mgr services to match the active mgr.
      count: 2
      allowMultiplePerNode: false
      modules:
        - name: rook
          enabled: true
    placement:
      all:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: oke.oraclecloud.com/pool.name
                  operator: In
                  values:
                  - rook
        # podAffinity:
        #   oke.oraclecloud.com/pool.name: rook
        tolerations:
        - key: "node-role.kubernetes.io/rook-node"
          operator: "Exists"
          effect: "NoSchedule"