apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc 
    namespace: istio-system
  # ignoreDifferences:
  #   - group: admissionregistration.k8s.io
  #     jsonPointers:
  #       - /webhooks/0/failurePolicy
  #     kind: ValidatingWebhookConfiguration
  #     name: istio-validator-istio-system
  #   - group: admissionregistration.k8s.io
  #     jsonPointers:
  #       - /webhooks/0/failurePolicy
  #     kind: ValidatingWebhookConfiguration
  #     name: istiod-default-validator
  project: default
  sources:
    - chart: base
      helm:
        releaseName: istio-base
        values: |
          defaultRevision: default
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.2
    # - chart: gateway
    #   helm:
    #     releaseName: gateway
    #     valuesObject:
    #       defaults:
    #         service:
    #           loadBalancerIP: 10.10.99.31
    #   repoURL: 'https://istio-release.storage.googleapis.com/charts'
    #   targetRevision: 1.22.1
    # - helm:
    #     releaseName: istio
    #   path: .
    #   repoURL: 'some-istio-repo'
    #   targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: istio-base
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://istio-release.storage.googleapis.com/charts
#     chart: base
#     targetRevision: '1.23.2'
#     helm:
#       releaseName: istio-base
#       values: |
#         defaultRevision: default
#   destination:
#     namespace: istio-system
#     server: https://kubernetes.default.svc 
#   syncPolicy:
#     automated: {}
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true