apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc 
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io                                                              
      kind: ValidatingWebhookConfiguration
      jsonPointers:                                                                                    
      - /webhooks/0/clientConfig/caBundle
      - /webhooks/0/failurePolicy
  project: default
  sources:
    - chart: base
      helm:
        releaseName: istio-base
        values: |
          defaultRevision: default
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.2
    - chart: istiod
      helm:
        releaseName: istiod
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
