apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc 
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io                                                              
      kind: ValidatingWebhookConfiguration
      jsonPointers:                                                                                    
      - /webhooks/0/clientConfig/caBundle
      - /webhooks/0/failurePolicy
  project: default
  sources:
    - chart: base
      helm:
        releaseName: istio-base
        values: |
          defaultRevision: default
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.2
    - chart: istiod
      helm:
        releaseName: istiod
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.2
    - chart: istiod
      helm:
        releaseName: istiod
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.2
    - chart: gateway
      helm:
        releaseName: istio-ingress
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.23.2
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value: |
              defaults:
                service:
                  type: LoadBalancer
                  ports:
                  - name: tcp-status-port
                    port: 15021
                    targetPort: 15021
                  - name: http
                    port: 80
                    targetPort: 8080
                  - name: tcp-postgres
                    port: 5432
                    targetPort: 5432
                  - name: https
                    port: 443
                    targetPort: 8081
                  annotations: 
                    oci.oraclecloud.com/load-balancer-type: "nlb"
                    oci-network-load-balancer.oraclecloud.com/internal: "false"
                    oci-network-load-balancer.oraclecloud.com/is-preserve-source: "false"
                    oci-network-load-balancer.oraclecloud.com/subnet: : <path:ocivault#nlb_subnet_oke_k8s_cluster#latest | base64decode>  
                  externalTrafficPolicy: "Local"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
