apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.23.2
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            defaults:
              service:
                type: LoadBalancer
                ports:
                - name: tcp-status-port
                  port: 15021
                  targetPort: 15021
                - name: http
                  port: 80
                  targetPort: 8080
                - name: tcp-postgres
                  port: 5432
                  targetPort: 5432
                - name: https
                  port: 443
                  targetPort: 8081
                annotations: 
                  oci.oraclecloud.com/load-balancer-type: "nlb"
                  oci-network-load-balancer.oraclecloud.com/internal: "false"
                  oci-network-load-balancer.oraclecloud.com/is-preserve-source: "false"
                  oci-network-load-balancer.oraclecloud.com/subnet: : <path:ocivault#nlb_subnet_oke_k8s_cluster#latest | base64decode>  
                externalTrafficPolicy: "Local"
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    automated:
      prune: true
      selfHeal: true
