apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.common.destination.server }}
    namespace: cnpg-system
  project: default
  source:
    repoURL: {{ .Values.common.source.repoURL }}
    targetRevision: {{ .Values.common.source.targetRevision }}
    path: common/postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
