apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.istioGw.destination.server }}
    namespace: istio-system
  project: default
  source:
    repoURL: {{ .Values.istioGw.source.repoURL }}
    targetRevision: {{ .Values.istioGw.source.targetRevision }}
    path: common/istio-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
