apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: functional-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sunbird-rc
    server: {{ .Values.common.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.common.source.repoURL }}
    targetRevision: {{ .Values.common.source.targetRevision }}
    path: workload/sunbird-rc
    plugin:
      name: argocd-vault-plugin-helm
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    automated:
      prune: true
      selfHeal: true