apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-share
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  artifactory_url_env: {{ .Values.artifacts.baseUrl }}
  iam_adapter_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.iamAdapter }}
  iam_adapter_regproc_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.iamAdapterRegproc }}
  iam_adapter_regproc_ext_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.iamAdapterRegprocExt }}
  zip_file_path: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.hsmClientZip }}
  cache_provider_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.cacheProvider }}
  runtime_dep_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.runtimeDep }}
  regproc_jars_env:  {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.regprocJars }}
  runtime_dep_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.runtimeDepUrl }}
  preregistration_i18n_bundle_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.preregistrationBundleUrl }}
  virusscanner_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.virusscannerUrl }}
  auth_wrapper_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.authwrapperUrl }}
  esignet_wrapper_url_env: {{ .Values.artifacts.baseUrl }}/{{ .Values.artifacts.esignetauthwrapperUrl }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: regclient-certs
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
binaryData:
  keystore.p12: {{ .Values.regclient_keystore_file }}
data:
  Client.crt: |
    {{ .Values.regclient_client_certificate | indent 4 }}
  Client.csr: |
    {{ .Values.regclient_client_csr | indent 4 }}
  Client.key: |
    {{ .Values.regclient_client_key | indent 4 }}
  RootCA.crt: |
    {{ .Values.regclient_root_certificate | indent 4 }}
  RootCA.key: |
    {{ .Values.regclient_root_key | indent 4 }}
