apiVersion: v1
kind: Secret
metadata:
  name: keystore-secret-env 
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
type: Opaque
stringData:
  keystore_secret_env: {{ .Values.regclient_keystore_password }}
