{{- if .Values.external.msg_gw_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msg-gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.external.destination.server }}
    namespace: msg-gateways
  project: default
  source:
    repoURL: {{ .Values.external.source.repoURL }}
    targetRevision: {{ .Values.external.source.targetRevision }}
    path: workload/mosip/external-modules/msg-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata: 
      labels:
        istio-injection: enabled   
{{- end }}