{{- if .Values.external.softhsm_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: softhsm-kernel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.external.destination.server }}
    namespace: softhsm
  project: default
  source:
    repoURL: {{ .Values.external.source.repoURL }}
    targetRevision: {{ .Values.external.source.targetRevision }}
    path: workload/mosip/external-modules/softhsm-kernel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata: 
      labels:
        istio-injection: enabled   

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: softhsm-ida
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.external.destination.server }}
    namespace: softhsm
  project: default
  source:
    repoURL: {{ .Values.external.source.repoURL }}
    targetRevision: {{ .Values.external.source.targetRevision }}
    path: workload/mosip/external-modules/softhsm-ida
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata: 
      labels:
        istio-injection: enabled   

{{- end }}