{{- if .Values.core.mock_mv_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-mv
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.core.destination.server }}
    namespace: abis
  project: default
  source:
    repoURL: {{ .Values.core.source.repoURL }}
    targetRevision: {{ .Values.core.source.targetRevision }}
    path: workload/mosip/core-modules/mock-mv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata: 
      labels:
        istio-injection: enabled   
{{- end }}