apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-data
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
