apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cassandra
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - port:
      number: 9042
      name: cassandra
      protocol: TCP
    hosts:
    - {{ .Values.cassandraHost }}
