apiVersion: v1
kind: Secret
metadata:
  name: super-user-secret
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  username: {{ .Values.super_username | b64enc | quote }}
  password: {{ .Values.super_user_password | b64enc | quote }}
type: Opaque