apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
type: Opaque
data:
  password: {{ .Values.pg_db_password | b64enc | quote }}
  username: {{ .Values.pg_db_user | b64enc | quote }}

---

apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: {{ .Values.pg_db_password | b64enc | quote }}
kind: Secret
metadata:
  name: superuser-secret
  annotations:
    argocd.argoproj.io/hook: PreSync
type: kubernetes.io/basic-auth