apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-install-sa
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-install-cls-role
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-install-cls-role-binding
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
subjects:
- kind: ServiceAccount
  name: postgres-install-sa 
  namespace: postgres
roleRef:
  kind: ClusterRole
  name: postgres-install-cls-role 
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: batch/v1
kind: Job
metadata:
  name: install-postgres
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: postgres-install-sa
      containers:
      - name: configmanager
        image: ghcr.io/oci-sunbird/ociop:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            cd /root/.oci/install &&        
            ./install.sh;                              
        volumeMounts:
        - name: install-volume
          mountPath: /root/.oci/install
      restartPolicy: Never
      volumes:
      - name: install-volume
        configMap:
          name: {{ .Chart.Name }}-install-config
