apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - 'api-internal.{{ .Values.ansibleenv.domain }}'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - 'api-internal.{{ .Values.ansibleenv.domain }}'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.domain_ssl_secret_name }}
      mode: SIMPLE

--- 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - 'api.{{ .Values.ansibleenv.domain }}'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - 'api.{{ .Values.ansibleenv.domain }}'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.domain_ssl_secret_name }}
      mode: SIMPLE
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-swagger
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingress
  action: DENY
  rules:
  - to:
    - operation:
        paths: ["*/swagger-ui.html", "*/swagger-ui/index.html"]

---

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingress
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
