apiVersion: v1
kind: Secret
metadata:
  name: oci-profile
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  tenancy: {{ .Values.oci.tenancy_id | b64enc | quote }}
  user: {{ .Values.oci.user_id | b64enc | quote }}
  region: {{ .Values.oci.region | b64enc | quote }}
  fingerprint: {{ .Values.oci.fingerprint | b64enc | quote }}
  privateKey: |-
    {{ .Values.oci.user_api_key | b64enc | indent 4 }}
  privateKeyPassphrase: ""