keycloak_istio_enabled: true
keycloakExternalHost: iam.<path:ocivault#mosip_domain#latest | base64decode> 
keycloak_db_password: <path:ocivault#mosip_pg_password#latest | base64decode> 


clientSecrets:
  - name: openg2p_admin_client_secret
    secret: <path:ocivault#openg2p_admin_client_secret#latest | base64decode>
  - name: openg2p_selfservice_client_secret
    secret: <path:ocivault#openg2p_selfservice_client_secret#latest | base64decode>
  - name: openg2p_serviceprovider_client_secret
    secret: <path:ocivault#openg2p_serviceprovider_client_secret#latest | base64decode>
  - name: openg2p_minio_client_secret
    secret: <path:ocivault#openg2p_minio_client_secret#latest | base64decode>
  - name: openg2p_kafka_client_secret
    secret: <path:ocivault#openg2p_kafka_client_secret#latest | base64decode>
  - name: openg2p_opensearch_client_secret
    secret: <path:ocivault#openg2p_opensearch_client_secret#latest | base64decode>
  - name: openg2p_superset_client_secret
    secret: <path:ocivault#openg2p_superset_client_secret#latest | base64decode>
  - name: mosip_abis_client_secret
    secret: "<path:ocivault#openg2p_mosip_abis_client_secret#latest | base64decode>"
  - name: mosip_admin_client_secret
    secret: "<path:ocivault#openg2p_mosip_admin_client_secret#latest | base64decode>"
  - name: mosip_admin_services_client_secret
    secret: "<path:ocivault#openg2p_mosip_admin_services_client_secret#latest | base64decode>"
  - name: mosip_auth_client_secret
    secret: "<path:ocivault#openg2p_mosip_auth_client_secret#latest | base64decode>"
  - name: mosip_crereq_client_secret
    secret: "<path:ocivault#openg2p_mosip_crereq_client_secret#latest | base64decode>"
  - name: mosip_creser_client_secret
    secret: "<path:ocivault#openg2p_mosip_creser_client_secret#latest | base64decode>"
  - name: mosip_datsha_client_secret
    secret: "<path:ocivault#openg2p_mosip_datsha_client_secret#latest | base64decode>"
  - name: mosip_ida_client_secret
    secret: "<path:ocivault#openg2p_mosip_ida_client_secret#latest | base64decode>"
  - name: mosip_misp_client_secret
    secret: "<path:ocivault#openg2p_mosip_misp_client_secret#latest | base64decode>"
  - name: mosip_pms_client_secret
    secret: "<path:ocivault#openg2p_mosip_pms_client_secret#latest | base64decode>"
  - name: mosip_policymanager_client_secret
    secret: "<path:ocivault#openg2p_mosip_policymanager_client_secret#latest | base64decode>"
  - name: mosip_reg_client_secret
    secret: "<path:ocivault#openg2p_mosip_reg_client_secret#latest | base64decode>"
  - name: mosip_regproc_client_secret
    secret: "<path:ocivault#openg2p_mosip_regproc_client_secret#latest | base64decode>"
  - name: mosip_resident_client_secret
    secret: "<path:ocivault#openg2p_mosip_resident_client_secret#latest | base64decode>"
  - name: mosip_prereg_client_secret
    secret: "<path:ocivault#openg2p_mosip_prereg_client_secret#latest | base64decode>"
  - name: mosip_creser_idpass_client_secret
    secret: "<path:ocivault#openg2p_mosip_creser_idpass_client_secret#latest | base64decode>"
  - name: mosip_syncdata_client_secret
    secret: "<path:ocivault#openg2p_mosip_syncdata_client_secret#latest | base64decode>"
  - name: mosip_deployment_client_secret
    secret: "<path:ocivault#openg2p_mosip_deployment_client_secret#latest | base64decode>"
  - name: mpartner_default_auth_secret
    secret: "<path:ocivault#openg2p_mpartner_default_auth_secret#latest | base64decode>"
  - name: mosip_idrepo_client_secret
    secret: "<path:ocivault#openg2p_mosip_idrepo_client_secret#latest | base64decode>"
  - name: mpartner_default_print_secret
    secret: "<path:ocivault#openg2p_mpartner_default_print_secret#latest | base64decode>"
  - name: mosip_hotlist_client_secret
    secret: "<path:ocivault#openg2p_mosip_hotlist_client_secret#latest | base64decode>"
  - name: mpartner_default_mobile_secret
    secret: "<path:ocivault#openg2p_mpartner_default_mobile_secret#latest | base64decode>"
  - name: mosip_digitalcard_client_secret
    secret: "<path:ocivault#openg2p_mosip_digitalcard_client_secret#latest | base64decode>"
  - name: mpartner_default_digitalcard_secret
    secret: "<path:ocivault#openg2p_mpartner_default_digitalcard_secret#latest | base64decode>"
  - name: mosip_testrig_client_secret
    secret: "<path:ocivault#openg2p_mosip_testrig_client_secret#latest | base64decode>"
  - name: mpartner_default_opencrvs_secret
    secret: "<path:ocivault#openg2p_mpartner_default_opencrvs_secret#latest | base64decode>"


keycloak:
  image: 
    repository: mosipid/mosip-keycloak
    tag: 16.1.1-debian-10-r85

  service:
    type: ClusterIP

  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.profile.feature.upload_scripts=enabled"
      #value: "-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.import=/config/realm-mosip.json"

  proxyAddressForwarding: true

  replicaCount: 1

  # Enable if replicaCount > 1
  serviceDiscovery:
    enabled: true

  resources:
    limits: {}
    #   cpu: 250m
    #   memory: 1Gi
    requests:
      cpu: 200m
      memory: 1000Mi

  rbac:
    create: true
    rules:
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - get
      - list

    
  initContainers:
    - name: postgres-checker
      image: jbergknoff/postgresql-client
      command:
        - 'sh'
        - '-c'
        - 'until pg_isready -U ${KEYCLOAK_DB_USERNAME} -h ${KEYCLOAK_DB_HOSTNAME} -p ${KEYCLOAK_DB_PORT:-5432} -d ${KEYCLOAK_DB_DBNAME:-bitnami_keycloak}; do sleep 3; done'
      env: 
        - name: KEYCLOAK_DB_HOSTNAME
          value: "postgres-postgresql.postgres"
        - name: KEYCLOAK_DB_USERNAME
          value: "bn_keycloak"
        - name: KEYCLOAK_DB_DBNAME
          value: "bitnami_keycloak"
  
  auth:
    adminUser: admin
    adminPassword: <path:ocivault#mosip_keycloak_admin_password#latest | base64decode>
  
  ingress:
    enabled: false
 
  postgresql:
    enabled: false
  
  externalDatabase:
    host: postgres-postgresql.postgres
    database: bitnami_keycloak
    user: bn_keycloak
    existingSecret: postgres-postgresql
    existingSecretPasswordKey: password
  