apiVersion: v1
kind: ConfigMap
metadata:
  name: global
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  installation-name: oci-mosip-sandbox
  installation-domain: {{ .Values.configserver.domain_name }}
  mosip-version: develop
  mosip-api-host: api.{{ .Values.configserver.domain_name }}
  mosip-api-internal-host: api-internal.{{ .Values.configserver.domain_name }}
  mosip-prereg-host: prereg.{{ .Values.configserver.domain_name }}
  mosip-activemq-host: activemq.{{ .Values.configserver.domain_name }}
  mosip-kibana-host: kibana.{{ .Values.configserver.domain_name }}
  mosip-admin-host: admin.{{ .Values.configserver.domain_name }}
  mosip-regclient-host: regclient.{{ .Values.configserver.domain_name }}
  mosip-minio-host: minio.{{ .Values.configserver.domain_name }}
  mosip-kafka-host: kafka.{{ .Values.configserver.domain_name }}
  mosip-iam-external-host: iam.{{ .Values.configserver.domain_name }}
  mosip-idp-host: idp.{{ .Values.configserver.domain_name }}
  mosip-postgres-host: postgres.{{ .Values.configserver.domain_name }}
  mosip-pmp-host: pmp.{{ .Values.configserver.domain_name }}
  mosip-resident-host: resident.{{ .Values.configserver.domain_name }}
  mosip-compliance-host: compliance.{{ .Values.configserver.domain_name }}
  mosip-esignet-host: esignet.{{ .Values.configserver.domain_name }}
  mosip-smtp-host: smtp.{{ .Values.configserver.domain_name }}
  is_glowroot_env: absent

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-share
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  active_profile_env: {{ .Values.configserver.activeProfileEnv }}
  cache_config_url_env: http://config-server.config-server/config/*/{{ .Values.configserver.activeProfileEnv }}/{{ .Values.configserver.gitRepo.version }}/hazelcast_cache.xml
  consolidator_config_file_url_env: http://config-server.config-server/config/*/{{ .Values.configserver.activeProfileEnv }}/{{ .Values.configserver.gitRepo.version }}/websub-consolidator.toml
  hub_config_file_url_env: http://config-server.config-server/config/*/{{ .Values.configserver.activeProfileEnv }}/{{ .Values.configserver.gitRepo.version }}/websub-service.toml
  spring_config_label_env: {{ .Values.configserver.gitRepo.version }}
  spring_config_url_env: http://config-server.config-server/config

---