
{{- if .Values.esignet_istio_enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: esignet
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - istio-system/all-hosts
  hosts:
    - {{.Values.esignet_hostname }}
  http:
    - match:
      - uri:
          prefix: /v1/mock-identity-system
      route:
        - destination:
            host: esignet-mock-identity-system
            port:
              number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https
        response:
          set:
            Cache-control: no-store
            Pragma: no-cache
            Strict-Transport-Security: max-age=31536000; includeSubDomains
            X-Frame-Options: SAMEORIGIN
    - match:
      - uri:
          prefix: /v1/esignet
      route:
        - destination:
            host: esignet
            port:
              number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https
        response:
          set:
            Cache-control: no-store
            Pragma: no-cache
            Strict-Transport-Security: max-age=31536000; includeSubDomains
            X-Frame-Options: SAMEORIGIN
    - route:
        - destination:
            host: esignet-oidc-ui
            port:
              number: 80
      headers:
        request:
          set:
            x-forwarded-proto: https
        response:
          set:
            Cache-control: no-store
            Pragma: no-cache
            Strict-Transport-Security: max-age=31536000; includeSubDomains
            X-Frame-Options: SAMEORIGIN

{{- end }}