apiVersion: v1
kind: Pod
metadata:
  name: control-center
spec:
  imagePullSecrets:
    - name: ocir
  containers:
    - name: control-center
      image: <path:ocivault#control-center-image#latest | base64decode> 
      imagePullPolicy: Always
      command: ["sh", "-c"]
      args:
        - 'while true; do echo "Running"; sleep 360000; done'
  restartPolicy: Always