# apiVersion: v1
# kind: Pod
# metadata:
#   name: control-center
# spec:
#   imagePullSecrets:
#     - name: ocir
#   containers:
#     - name: control-center
#       image: <path:ocivault#control-center-image#latest | base64decode> 
#       imagePullPolicy: Always
#       command: ["sh", "-c"]
#       args:
#         - 'while true; do echo "Running"; sleep 360000; done'
#   restartPolicy: Always

# --- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: <path:ocivault#control-center-image#latest | base64decode>
        imagePullPolicy: Always 
        command: ["sh", "-c"]
        args:
          - 'while true; do echo "Running"; sleep 360000; done'
      imagePullSecrets:
        - name: ocir 
